import { CalendarDays } from 'lucide-react'
import { lessons } from '../data/lessons'
import { studyMetrics } from '../lib/metrics'
import { useAppState } from '../hooks/useAppState'

export function CalendarPage(){
  const {data}=useAppState(); const metrics=studyMetrics(data); const now=new Date(); const year=now.getFullYear(); const month=now.getMonth(); const first=new Date(year,month,1); const days=new Date(year,month+1,0).getDate(); const offset=first.getDay()
  const cells=Array.from({length:offset+days},(_,i)=>i<offset?null:i-offset+1)
  const sessionsFor=(day:number)=>{const key=`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;return data.studySessions.filter(s=>s.startedAt.slice(0,10)===key)}
  const monthName=now.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})
  return <div className="page calendar-page"><section className="page-header glass-panel"><CalendarDays className="mega-icon-svg"/><div><span className="eyebrow">Ritmo de estudos</span><h1>Calendário</h1><p>Veja quando estudou, por quanto tempo e o que abriu — sem bronca por dias vazios.</p></div></section><section className="calendar-summary stats-grid"><article className="stat-card glass-panel"><strong>{metrics.streak}</strong><span>dias de sequência</span></article><article className="stat-card glass-panel"><strong>{metrics.monthlyMinutes}</strong><span>minutos neste mês</span></article><article className="stat-card glass-panel"><strong>{metrics.studyDays.filter(d=>d.startsWith(`${year}-${String(month+1).padStart(2,'0')}`)).length}</strong><span>dias estudados no mês</span></article></section><section className="glass-panel content-panel"><div className="section-heading"><h2>{monthName}</h2><small>Quanto mais tempo, mais preenchido o dia.</small></div><div className="calendar-weekdays">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{cells.map((day,i)=>{if(day===null)return <span className="calendar-empty" key={`e-${i}`}/>;const sessions=sessionsFor(day);const minutes=sessions.reduce((a,s)=>a+s.minutes,0);const level=minutes===0?0:minutes<10?1:minutes<25?2:minutes<45?3:4;return <article key={day} className={`calendar-day level-${level}`}><strong>{day}</strong>{minutes>0?<><span>{minutes} min</span><small>{sessions.length} sessão(ões)</small></>:<small>—</small>}</article>})}</div></section><section className="glass-panel content-panel"><h2>Sessões recentes</h2>{data.studySessions.length===0?<p className="muted">Quando você concluir aulas ou usar o modo foco, as sessões aparecem aqui.</p>:<div className="session-list">{[...data.studySessions].reverse().slice(0,30).map(session=>{const lesson=lessons.find(l=>l.id===session.lessonId);return <article key={session.id}><div><strong>{lesson?.title??(session.course?session.course:'Sessão de estudo')}</strong><small>{new Date(session.startedAt).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}</small></div><span>{session.minutes} min</span></article>})}</div>}</section></div>
}
