import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Building2, ExternalLink, Save } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { countries } from '../data/countries'
import { WagePanel } from '../components/WagePanel'
import { useAppState } from '../hooks/useAppState'

interface CostDraft {rent:string;food:string;transport:string;utilities:string;internet:string;phone:string;leisure:string;sourceUrl:string;sourceLabel:string;checkedAt:string}
const empty:CostDraft={rent:'',food:'',transport:'',utilities:'',internet:'',phone:'',leisure:'',sourceUrl:'',sourceLabel:'',checkedAt:''}
const slug=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
function key(countryId:string,city:string){return `futuro-lab-city-cost:${countryId}:${slug(city)}`}
function read(countryId:string,city:string):CostDraft{try{return {...empty,...JSON.parse(localStorage.getItem(key(countryId,city))??'{}')}}catch{return empty}}

export function CityDetailPage(){
  const {countryId,citySlug}=useParams(); const country=countries.find(c=>c.id===countryId); const city=country?.cities.find(c=>slug(c)===citySlug); const {markCityResearched,recordRecent}=useAppState(); const [draft,setDraft]=useState<CostDraft>(()=>country&&city?read(country.id,city):empty); const [saved,setSaved]=useState(false)
  useEffect(()=>{if(!country||!city)return;markCityResearched(`${country.id}:${slug(city)}`);recordRecent({id:`${country.id}:${slug(city)}`,type:'city',title:`${city}, ${country.name}`,path:`/cities/${country.id}/${slug(city)}`})},[country?.id,city])
  useEffect(()=>{if(country&&city)setDraft(read(country.id,city))},[country?.id,city])
  if(!country||!city)return <div className="page"><h1>Cidade não encontrada</h1><Link to="/cities">Voltar às cidades</Link></div>
  const values=['rent','food','transport','utilities','internet','phone','leisure'] as const; const total=values.reduce((sum,k)=>sum+(Number(draft[k])||0),0); const hasValues=values.some(k=>Number(draft[k])>0)
  const save=()=>{localStorage.setItem(key(country.id,city),JSON.stringify(draft));setSaved(true);setTimeout(()=>setSaved(false),1500)}
  return <div className="page city-detail-page"><nav className="breadcrumbs"><Link to="/countries">Países</Link><span>›</span><Link to={`/countries/${country.id}`}>{country.name}</Link><span>›</span><span>{city}</span></nav><section className="page-header glass-panel"><Building2 className="mega-icon-svg"/><div><span className="eyebrow">{country.flag} {country.name} • {country.region}</span><h1>{city}</h1><p>Ficha de pesquisa local: idioma, clima, salário-base do país e uma planilha de custo de vida com fonte e data.</p></div></section>
    <div className="split-grid"><section className="glass-panel content-panel"><h2>Contexto</h2><dl className="facts"><div><dt>País</dt><dd>{country.name}</dd></div><div><dt>Moeda</dt><dd>{country.currency}</dd></div><div><dt>Idioma(s)</dt><dd>{country.languages.join(', ')}</dd></div><div><dt>Clima geral do país</dt><dd>{country.climate}</dd></div></dl><h3>Por que pesquisar a cidade separadamente?</h3><p>Aluguel, transporte, oportunidades e ritmo de vida podem mudar muito dentro do mesmo país. Não use a média nacional como se fosse a realidade desta cidade.</p></section><section className="glass-panel content-panel"><h2>Checklist da cidade</h2><ul><li>🏠 Pesquisar bairros e aluguel.</li><li>🚇 Ver transporte e tempo até estudo/trabalho.</li><li>💼 Conferir vagas da sua profissão.</li><li>🏥 Entender acesso a saúde e seguro.</li><li>🎓 Ver escolas, cursos ou universidades.</li><li>🌦️ Conferir clima mês a mês.</li><li>🛂 Confirmar se seu status migratório permite morar/trabalhar aqui.</li></ul></section></div>
    <WagePanel countryId={country.id}/>
    <section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Custo de vida</span><h2>Planilha mensal de {city}</h2></div><span className="pill">{country.currency}</span></div><div className="warning-box">🟠 O site não preenche aluguel ou despesas com números inventados. Registre valores de uma fonte que você pesquisou e guarde a data.</div><div className="city-cost-grid"><label>Aluguel<input type="number" min="0" value={draft.rent} onChange={e=>setDraft(d=>({...d,rent:e.target.value}))}/></label><label>Mercado/comida<input type="number" min="0" value={draft.food} onChange={e=>setDraft(d=>({...d,food:e.target.value}))}/></label><label>Transporte<input type="number" min="0" value={draft.transport} onChange={e=>setDraft(d=>({...d,transport:e.target.value}))}/></label><label>Energia/água<input type="number" min="0" value={draft.utilities} onChange={e=>setDraft(d=>({...d,utilities:e.target.value}))}/></label><label>Internet<input type="number" min="0" value={draft.internet} onChange={e=>setDraft(d=>({...d,internet:e.target.value}))}/></label><label>Telefone<input type="number" min="0" value={draft.phone} onChange={e=>setDraft(d=>({...d,phone:e.target.value}))}/></label><label>Lazer<input type="number" min="0" value={draft.leisure} onChange={e=>setDraft(d=>({...d,leisure:e.target.value}))}/></label></div><div className="calc-result"><span>Total mensal da sua pesquisa</span><strong>{hasValues?`${total.toLocaleString('pt-BR',{maximumFractionDigits:2})} ${country.currency}`:'—'}</strong><small>Esse total reflete somente os campos preenchidos por você.</small></div><div className="city-source-grid"><label>Nome da fonte<input value={draft.sourceLabel} onChange={e=>setDraft(d=>({...d,sourceLabel:e.target.value}))} placeholder="Ex.: site oficial de transporte + pesquisa de aluguel"/></label><label>Link da fonte<input type="url" value={draft.sourceUrl} onChange={e=>setDraft(d=>({...d,sourceUrl:e.target.value}))} placeholder="https://..."/></label><label>Data da pesquisa<input type="date" value={draft.checkedAt} onChange={e=>setDraft(d=>({...d,checkedAt:e.target.value}))}/></label><button className="primary-button" onClick={save}><Save size={17}/>{saved?'Salvo!':'Salvar pesquisa'}</button></div>{draft.sourceUrl&&<a className="source-link" href={draft.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink size={14}/> {draft.sourceLabel||'Abrir fonte registrada'}</a>}</section>
    <Link className="secondary-button" to="/cities"><ArrowLeft size={17}/> Voltar às cidades</Link>
  </div>
}
