import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Building2, ExternalLink, Save } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { countries } from '../data/countries'
import { WagePanel } from '../components/WagePanel'
import { useAppState } from '../hooks/useAppState'
import type { CityCostProfile } from '../types'

interface CostDraft {roomRent:string;apartmentRent:string;food:string;transport:string;utilities:string;internet:string;phone:string;leisure:string;sourceUrl:string;sourceName:string;publishedAt:string;retrievedAt:string}
const empty:CostDraft={roomRent:'',apartmentRent:'',food:'',transport:'',utilities:'',internet:'',phone:'',leisure:'',sourceUrl:'',sourceName:'',publishedAt:'',retrievedAt:''}
const slug=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const profileId=(countryId:string,city:string)=>`${countryId}:${slug(city)}`
const toDraft=(profile?:CityCostProfile):CostDraft=>profile?{roomRent:String(profile.roomRent||''),apartmentRent:String(profile.apartmentRent||''),food:String(profile.food||''),transport:String(profile.transport||''),utilities:String(profile.utilities||''),internet:String(profile.internet||''),phone:String(profile.phone||''),leisure:String(profile.leisure||''),sourceUrl:profile.sourceUrl,sourceName:profile.sourceName,publishedAt:profile.publishedAt??'',retrievedAt:profile.retrievedAt}:empty

export function CityDetailPage(){
  const {countryId,citySlug}=useParams(); const country=countries.find(c=>c.id===countryId); const city=country?.cities.find(c=>slug(c)===citySlug); const {data,replaceData,markCityResearched,recordRecent}=useAppState(); const id=country&&city?profileId(country.id,city):''; const stored=id?data.cityCosts[id]:undefined; const [draft,setDraft]=useState<CostDraft>(()=>toDraft(stored)); const [saved,setSaved]=useState(false); const [salary,setSalary]=useState(0)
  useEffect(()=>{if(!country||!city)return;markCityResearched(`${country.id}:${slug(city)}`);recordRecent({id:`${country.id}:${slug(city)}`,type:'city',title:`${city}, ${country.name}`,path:`/cities/${country.id}/${slug(city)}`})},[country?.id,city])
  useEffect(()=>setDraft(toDraft(stored)),[id,stored?.updatedAt])
  if(!country||!city)return <div className="page"><h1>Cidade não encontrada</h1><Link to="/cities">Voltar às cidades</Link></div>
  const values=['apartmentRent','food','transport','utilities','internet','phone','leisure'] as const; const total=values.reduce((sum,k)=>sum+(Number(draft[k])||0),0); const roomTotal=(Number(draft.roomRent)||0)+values.filter(k=>k!=='apartmentRent').reduce((sum,k)=>sum+(Number(draft[k])||0),0); const hasValues=values.some(k=>Number(draft[k])>0)||Number(draft.roomRent)>0
  const save=()=>{const now=new Date().toISOString();const profile:CityCostProfile={id,countryId:country.id,city,roomRent:Number(draft.roomRent)||0,apartmentRent:Number(draft.apartmentRent)||0,food:Number(draft.food)||0,transport:Number(draft.transport)||0,utilities:Number(draft.utilities)||0,internet:Number(draft.internet)||0,phone:Number(draft.phone)||0,leisure:Number(draft.leisure)||0,sourceName:draft.sourceName.trim(),sourceUrl:draft.sourceUrl.trim(),publishedAt:draft.publishedAt||undefined,retrievedAt:draft.retrievedAt||now.slice(0,10),updatedAt:now};replaceData({...data,cityCosts:{...data.cityCosts,[id]:profile},updatedAt:now});setSaved(true);setTimeout(()=>setSaved(false),1500)}
  const leftover=salary>0?salary-(Number(draft.apartmentRent)||0)-(Number(draft.food)||0)-(Number(draft.transport)||0)-(Number(draft.utilities)||0)-(Number(draft.internet)||0)-(Number(draft.phone)||0)-(Number(draft.leisure)||0):null
  return <div className="page city-detail-page"><nav className="breadcrumbs"><Link to="/countries">Países</Link><span>›</span><Link to={`/countries/${country.id}`}>{country.name}</Link><span>›</span><span>{city}</span></nav><section className="page-header glass-panel"><Building2 className="mega-icon-svg"/><div><span className="eyebrow">{country.flag} {country.name} • {country.region}</span><h1>{city}</h1><p>Pesquise a cidade separadamente do país. Salários, aluguel, transporte e rotina podem mudar bastante de um lugar para outro.</p></div></section>
    <div className="split-grid"><section className="glass-panel content-panel"><h2>Contexto</h2><dl className="facts"><div><dt>País</dt><dd>{country.name}</dd></div><div><dt>Moeda</dt><dd>{country.currency}</dd></div><div><dt>Idioma(s)</dt><dd>{country.languages.join(', ')}</dd></div><div><dt>Clima geral</dt><dd>{country.climate}</dd></div></dl><h3>Checklist</h3><ul><li>🏠 Bairros e aluguel.</li><li>🚇 Transporte até estudo/trabalho.</li><li>💼 Vagas da sua profissão.</li><li>🏥 Saúde e seguro.</li><li>🎓 Cursos e instituições.</li><li>🌦️ Clima mês a mês.</li><li>🛂 Regra migratória aplicável.</li></ul></section><section className="glass-panel content-panel"><h2>Orçamento de vida</h2><label>Salário líquido mensal na moeda local<input type="number" min="0" value={salary||''} onChange={e=>setSalary(Number(e.target.value))}/></label><div className="calc-result"><span>Sobra usando apartamento</span><strong>{leftover===null?'—':leftover.toLocaleString('pt-BR',{maximumFractionDigits:2})}</strong><small>Estimativa baseada nos valores que você registrou abaixo. Não é previsão garantida.</small></div><Link className="text-link" to={`/compare-cities?first=${encodeURIComponent(id)}`}>Comparar esta cidade →</Link></section></div>
    <WagePanel countryId={country.id}/>
    <section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Custo de vida</span><h2>Pesquisa mensal de {city}</h2></div><span className="pill">{country.currency}</span></div><div className="warning-box">🟠 O Futuro Lab não inventa números. Preencha usando uma fonte pesquisada e guarde a data. Ao entrar na sua conta, esta ficha também sincroniza.</div><div className="city-cost-grid"><label>Quarto compartilhado<input type="number" min="0" value={draft.roomRent} onChange={e=>setDraft(d=>({...d,roomRent:e.target.value}))}/></label><label>Apartamento<input type="number" min="0" value={draft.apartmentRent} onChange={e=>setDraft(d=>({...d,apartmentRent:e.target.value}))}/></label><label>Mercado/comida<input type="number" min="0" value={draft.food} onChange={e=>setDraft(d=>({...d,food:e.target.value}))}/></label><label>Transporte<input type="number" min="0" value={draft.transport} onChange={e=>setDraft(d=>({...d,transport:e.target.value}))}/></label><label>Energia/água<input type="number" min="0" value={draft.utilities} onChange={e=>setDraft(d=>({...d,utilities:e.target.value}))}/></label><label>Internet<input type="number" min="0" value={draft.internet} onChange={e=>setDraft(d=>({...d,internet:e.target.value}))}/></label><label>Telefone<input type="number" min="0" value={draft.phone} onChange={e=>setDraft(d=>({...d,phone:e.target.value}))}/></label><label>Lazer<input type="number" min="0" value={draft.leisure} onChange={e=>setDraft(d=>({...d,leisure:e.target.value}))}/></label></div><div className="split-grid"><div className="calc-result"><span>Total com apartamento</span><strong>{hasValues?total.toLocaleString('pt-BR',{maximumFractionDigits:2}):'—'}</strong></div><div className="calc-result"><span>Total com quarto</span><strong>{hasValues?roomTotal.toLocaleString('pt-BR',{maximumFractionDigits:2}):'—'}</strong></div></div><div className="city-source-grid"><label>Fonte<input value={draft.sourceName} onChange={e=>setDraft(d=>({...d,sourceName:e.target.value}))} placeholder="Ex.: órgão de transporte + pesquisa de aluguel"/></label><label>Link<input type="url" value={draft.sourceUrl} onChange={e=>setDraft(d=>({...d,sourceUrl:e.target.value}))} placeholder="https://..."/></label><label>Publicado em<input type="date" value={draft.publishedAt} onChange={e=>setDraft(d=>({...d,publishedAt:e.target.value}))}/></label><label>Consultado em<input type="date" value={draft.retrievedAt} onChange={e=>setDraft(d=>({...d,retrievedAt:e.target.value}))}/></label><button className="primary-button" onClick={save}><Save size={17}/>{saved?'Salvo e pronto para sincronizar':'Salvar pesquisa'}</button></div>{draft.sourceUrl&&<a className="source-link" href={draft.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink size={14}/> {draft.sourceName||'Abrir fonte registrada'}</a>}</section>
    <Link className="secondary-button" to="/cities"><ArrowLeft size={17}/> Voltar às cidades</Link>
  </div>
}
