import { useMemo, useState } from 'react'
import { CheckCircle2, Code2, Lightbulb, RotateCcw, XCircle } from 'lucide-react'
import { codeChallenges } from '../data/codeChallenges'
import { useAppState } from '../hooks/useAppState'

export function CodeChallengesPage(){
 const {data,saveCodeChallengeProgress}=useAppState(); const [index,setIndex]=useState(0); const challenge=codeChallenges[index]; const saved=data.codeChallengeProgress[challenge.id]; const [code,setCode]=useState(saved?.code??challenge.starter); const [hint,setHint]=useState(0); const [checked,setChecked]=useState(false)
 const results=useMemo(()=>challenge.checks.map(check=>({label:check.label,pass:check.pattern.test(code)})),[challenge,code]); const passed=results.every(x=>x.pass)
 const persist=(nextCode=code,complete=false)=>saveCodeChallengeProgress({challengeId:challenge.id,code:nextCode,completedAt:complete?new Date().toISOString():saved?.completedAt,updatedAt:new Date().toISOString()})
 const choose=(next:number)=>{const safe=(next+codeChallenges.length)%codeChallenges.length;persist();setIndex(safe);const nextChallenge=codeChallenges[safe];setCode(data.codeChallengeProgress[nextChallenge.id]?.code??nextChallenge.starter);setHint(0);setChecked(false)}
 const check=()=>{setChecked(true);persist(code,passed)}
 return <div className="page code-challenges-page"><section className="page-header glass-panel"><Code2 className="mega-icon-svg"/><div><span className="eyebrow">Prática com correção</span><h1>Desafios de código</h1><p>{codeChallenges.length} desafios iniciais de JavaScript, HTML e CSS. O código fica salvo e entra na sincronização da sua conta.</p></div></section><div className="challenge-layout"><aside className="glass-panel challenge-list">{codeChallenges.map((item,i)=>{const done=!!data.codeChallengeProgress[item.id]?.completedAt;return <button key={item.id} className={i===index?'active':''} onClick={()=>choose(i)}><span>{done?'✅':i===index?'🟡':'○'}</span><div><strong>{item.title}</strong><small>{item.language} • {item.level}</small></div></button>})}</aside><section className="glass-panel content-panel challenge-editor"><span className="eyebrow">{challenge.language} • {challenge.level} • {index+1}/{codeChallenges.length}</span><h2>{challenge.title}</h2><p>{challenge.instruction}</p><label>Seu código<textarea spellCheck={false} rows={14} value={code} onChange={e=>{setCode(e.target.value);setChecked(false);persist(e.target.value)}}/></label><div className="button-row"><button className="primary-button" onClick={check}>Testar código</button><button className="secondary-button" onClick={()=>{setHint(v=>Math.min(challenge.hints.length,v+1));setChecked(false)}}><Lightbulb size={17}/> Dica</button><button className="secondary-button" onClick={()=>{setCode(challenge.starter);setHint(0);setChecked(false);persist(challenge.starter)}}><RotateCcw size={17}/> Resetar</button></div>{hint>0&&<div className="hint-stack">{challenge.hints.slice(0,hint).map((text,i)=><div className="tip-box" key={text}><strong>Dica {i+1}</strong><p>{text}</p></div>)}</div>}{checked&&<div className="test-results">{results.map(result=><div className={result.pass?'test-pass':'test-fail'} key={result.label}>{result.pass?<CheckCircle2/>:<XCircle/>}<span>{result.label}</span></div>)}<div className={passed?'feedback ok':'feedback bad'}>{passed?'Tudo passou! ✅ Desafio concluído e salvo.':'Ainda falta alguma coisa. Use as dicas ou compare com a solução.'}</div></div>}<details className="solution-box"><summary>Ver solução</summary><pre><code>{challenge.solution}</code></pre></details><div className="button-row"><button className="secondary-button" onClick={()=>choose(index-1)}>← Anterior</button><button className="secondary-button" onClick={()=>choose(index+1)}>Próximo →</button></div></section></div></div>
}
