import { ArrowLeft, ExternalLink, Heart, ShieldCheck, TriangleAlert } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { countries } from '../data/countries'
import { countryCurrent } from '../data/countryCurrent'
import { useAppState } from '../hooks/useAppState'

export function CountryPage(){
 const {id}=useParams(); const c=countries.find(x=>x.id===id); const {data,toggleFavorite}=useAppState(); if(!c)return <div className="page"><h1>País não encontrado</h1></div>
 const favId=`country:${c.id}`; const fav=data.favorites.includes(favId); const verified=countryCurrent[c.id]
 return <div className="page"><Link className="back-link" to="/countries"><ArrowLeft size={18}/> países</Link><section className="country-hero glass-panel"><div className="giant-flag">{c.flag}</div><div><span className="eyebrow">{c.region}</span><h1>{c.name}</h1><p>{c.capital} • {c.currency}</p><div className="tags">{c.languages.map(x=><span key={x}>{x}</span>)}</div></div><button className="icon-button big" onClick={()=>toggleFavorite(favId)} aria-label="Favoritar país"><Heart fill={fav?'currentColor':'none'}/></button></section><div className="split-grid"><section className="glass-panel content-panel"><h2>Visão geral</h2><dl className="facts"><div><dt>Capital</dt><dd>{c.capital}</dd></div><div><dt>Moeda</dt><dd>{c.currency}</dd></div><div><dt>Idioma(s)</dt><dd>{c.languages.join(', ')}</dd></div><div><dt>Clima</dt><dd>{c.climate}</dd></div></dl><h3>Cidades para pesquisar</h3><div className="chip-row">{c.cities.map(x=><span className="chip static" key={x}>{x}</span>)}</div></section><section className="glass-panel content-panel"><h2>Para quem pode fazer sentido</h2><ul>{c.bestFor.map(x=><li key={x}>👍 {x}</li>)}</ul><h3>Pode ser mais difícil para quem...</h3><ul>{c.harderFor.map(x=><li key={x}>• {x}</li>)}</ul></section></div><div className="split-grid"><section className="glass-panel content-panel good"><h2><ShieldCheck/> Pontos positivos</h2>{c.pros.map(x=><p key={x}>• {x}</p>)}</section><section className="glass-panel content-panel caution"><h2><TriangleAlert/> Pontos de atenção</h2>{c.cons.map(x=><p key={x}>• {x}</p>)}</section></div>
 {verified?<section className="glass-panel dynamic-data verified-data"><div className="section-heading"><div><span className="eyebrow">Dados verificados</span><h2>Trabalho, estudo e imigração</h2></div><span className="pill">Atualizado {verified.updatedAt.split('-').reverse().join('/')}</span></div>{verified.minimumWage&&<div className="verified-highlight"><strong>💼 Salário mínimo</strong><h3>{verified.minimumWage.value}</h3><p>{verified.minimumWage.note}</p></div>}<div className="split-grid"><div><h3>🎓 Estudar e trabalhar</h3>{verified.studyWork?.map(x=><p key={x}>• {x}</p>)}</div><div><h3>🛂 Imigração e permissões</h3>{verified.immigrationHighlights?.map(x=><p key={x}>• {x}</p>)}</div></div><div className="source-list"><h3>Fontes oficiais</h3>{verified.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.label}<ExternalLink size={14}/></a>)}</div><small>Regras e valores podem mudar. Confirme novamente nas fontes oficiais antes de tomar decisões.</small></section>:<section className="glass-panel dynamic-data"><h2>Salários, custo de vida e imigração</h2><p>{c.dynamicNote}</p><div className="placeholder-grid"><div><strong>💼 Salários</strong><span>Dados atuais ainda não carregados</span></div><div><strong>🏠 Custo de vida</strong><span>Dados atuais ainda não carregados</span></div><div><strong>🛂 Imigração</strong><span>Confirmar em fonte oficial antes de decidir</span></div><div><strong>🎓 Estudo</strong><span>Regras variam por curso e permissão</span></div></div><small>Fonte-base: {c.sources[0]}</small></section>}
 </div>
}
