import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { GitCompareArrows, Search, WalletCards } from 'lucide-react'
import { countries } from '../data/countries'
import { wageByCountry } from '../data/wages'
import { useFxRates } from '../hooks/useFxRates'
import { convertNativeToBRL, formatBRL, formatMoney, hourlyEquivalent, monthlyEquivalent } from '../lib/wageMath'

export function CountriesPage(){
 const [q,setQ]=useState(''); const [selected,setSelected]=useState<string[]>([]); const fx=useFxRates()
 const filtered=useMemo(()=>countries.filter(c=>`${c.name} ${c.capital} ${c.languages.join(' ')} ${c.cities.join(' ')}`.toLowerCase().includes(q.toLowerCase())),[q])
 const chosen=countries.filter(c=>selected.includes(c.id)); const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length<4?[...s,id]:s)
 const wageCell=(countryId:string,kind:'hour'|'month'|'brl')=>{const wage=wageByCountry[countryId];if(!wage)return '—';const hourly=hourlyEquivalent(wage);const monthly=monthlyEquivalent(wage);if(kind==='hour')return hourly!=null?`${formatMoney(hourly,wage.currency)}/h`:wage.headline;if(kind==='month')return monthly!=null?`${formatMoney(monthly,wage.currency)}/mês`:wage.headline;const converted=convertNativeToBRL(monthly,wage.currency,fx.rates);return converted!=null?`${formatBRL(converted)}/mês`:'—'}
 return <div className="page"><section className="page-header glass-panel"><div className="mega-icon">🌍</div><div><span className="eyebrow">Vida no exterior</span><h1>Países</h1><p>{countries.length} países para explorar. Dados dinâmicos só aparecem quando possuem fonte e data.</p><div className="hero-actions"><Link className="secondary-button" to="/salaries"><WalletCards size={18}/> Comparar salários em reais</Link></div></div></section><div className="toolbar glass-panel"><div className="inline-input"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar país, capital, cidade ou idioma..."/></div><span>{selected.length}/4 no comparador</span></div>{chosen.length>1&&<section className="comparison glass-panel"><div className="section-heading"><h2><GitCompareArrows size={22}/> Comparação rápida</h2></div><div className="comparison-table"><div className="compare-row head"><span>Critério</span>{chosen.map(c=><strong key={c.id}>{c.flag} {c.name}</strong>)}</div>{[['Capital','capital'],['Moeda','currency'],['Idioma','languages'],['Clima','climate']].map(([label,key])=><div className="compare-row" key={key}><span>{label}</span>{chosen.map(c=><span key={c.id}>{Array.isArray(c[key as keyof typeof c])?(c[key as keyof typeof c] as string[]).join(', '):String(c[key as keyof typeof c])}</span>)}</div>)}<div className="compare-row"><span>Piso / hora</span>{chosen.map(c=><span key={c.id}>{wageCell(c.id,'hour')}</span>)}</div><div className="compare-row"><span>Equiv. / mês</span>{chosen.map(c=><span key={c.id}>{wageCell(c.id,'month')}</span>)}</div><div className="compare-row"><span>≈ em reais</span>{chosen.map(c=><span key={c.id}>{wageCell(c.id,'brl')}</span>)}</div></div><small>Salário mínimo/piso é bruto e não é salário médio de uma profissão. Países sem piso nacional único mostram a regra regional/setorial. Conversão em R$ depende do câmbio disponível.</small></section>}<div className="country-grid">{filtered.map(c=><article className="country-card glass-panel" key={c.id}><div className="country-top"><span className="flag">{c.flag}</span><button className={selected.includes(c.id)?'chip selected':'chip'} onClick={()=>toggle(c.id)}>{selected.includes(c.id)?'Comparando':'Comparar'}</button></div><Link to={`/countries/${c.id}`}><h3>{c.name}</h3><p>{c.capital} • {c.currency}</p><small>{c.languages.join(' • ')}</small><div className="tags">{c.bestFor.slice(0,3).map(x=><span key={x}>{x}</span>)}</div></Link></article>)}</div></div>
}
