import { useMemo, useState } from 'react'
import { GitCompareArrows, SlidersHorizontal } from 'lucide-react'
import { Link } from 'react-router-dom'
import { countries } from '../data/countries'
import { wageByCountry } from '../data/wages'
import { useFxRates } from '../hooks/useFxRates'
import { convertNativeToBRL, formatBRL, formatMoney, hourlyEquivalent, monthlyEquivalent } from '../lib/wageMath'

const criteria=[['salary','Salário'],['cost','Custo'],['safety','Segurança'],['climate','Clima'],['language','Idioma'],['immigration','Imigração'],['health','Saúde'],['career','Carreira'],['education','Educação']] as const
type Criterion=typeof criteria[number][0]
type Ratings=Record<string,Partial<Record<Criterion,number>>>
const ratingKey='futuro-lab-country-ratings-v1'
function readRatings():Ratings{try{return JSON.parse(localStorage.getItem(ratingKey)??'{}') as Ratings}catch{return {}}}

export function CountryComparePage(){
  const fx=useFxRates(); const [selected,setSelected]=useState<string[]>(['irlanda','canada']); const [weights,setWeights]=useState<Record<Criterion,number>>({salary:5,cost:4,safety:5,climate:2,language:5,immigration:5,health:3,career:5,education:3}); const [ratings,setRatings]=useState<Ratings>(readRatings)
  const chosen=countries.filter(c=>selected.includes(c.id)); const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(x=>x!==id):current.length<4?[...current,id]:current)
  const setRating=(countryId:string,criterion:Criterion,value:number)=>{const next={...ratings,[countryId]:{...ratings[countryId],[criterion]:value}};setRatings(next);localStorage.setItem(ratingKey,JSON.stringify(next))}
  const score=(countryId:string)=>{let earned=0,max=0;for(const [key] of criteria){const weight=weights[key];const rating=ratings[countryId]?.[key];max+=weight*5;if(rating)earned+=weight*rating}return max?Math.round(earned/max*100):0}
  const ranking=useMemo(()=>[...chosen].sort((a,b)=>score(b.id)-score(a.id)),[chosen,ratings,weights])
  const wage=(id:string)=>wageByCountry[id]
  return <div className="page compare-page"><section className="page-header glass-panel"><GitCompareArrows className="mega-icon-svg"/><div><span className="eyebrow">Comparador pessoal</span><h1>Compare até 4 países</h1><p>Dados objetivos ficam separados das suas notas pessoais. O ranking usa somente as avaliações que você escolheu, ponderadas pela importância de cada critério.</p></div></section>
    <section className="glass-panel content-panel"><h2>1. Escolha os países</h2><div className="compare-country-picker">{countries.map(c=><button key={c.id} className={selected.includes(c.id)?'country-choice selected':'country-choice'} onClick={()=>toggle(c.id)}><span>{c.flag}</span><strong>{c.name}</strong></button>)}</div><small>{selected.length}/4 selecionados.</small></section>
    {chosen.length>0&&<><section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow"><SlidersHorizontal size={15}/> Suas prioridades</span><h2>2. Diga o que pesa mais</h2></div></div><div className="weight-grid">{criteria.map(([key,label])=><label key={key}><span>{label}<strong>{weights[key]}/5</strong></span><input type="range" min="0" max="5" step="1" value={weights[key]} onChange={e=>setWeights(w=>({...w,[key]:Number(e.target.value)}))}/></label>)}</div></section>
      <section className="glass-panel content-panel"><h2>3. Compare fatos disponíveis</h2><div className="comparison-table wide"><div className="compare-row head"><span>Critério</span>{chosen.map(c=><strong key={c.id}>{c.flag} {c.name}</strong>)}</div><div className="compare-row"><span>Capital</span>{chosen.map(c=><span key={c.id}>{c.capital}</span>)}</div><div className="compare-row"><span>Moeda</span>{chosen.map(c=><span key={c.id}>{c.currency}</span>)}</div><div className="compare-row"><span>Idioma</span>{chosen.map(c=><span key={c.id}>{c.languages.join(', ')}</span>)}</div><div className="compare-row"><span>Clima</span>{chosen.map(c=><span key={c.id}>{c.climate}</span>)}</div><div className="compare-row"><span>Piso por hora</span>{chosen.map(c=>{const w=wage(c.id);const hourly=w?hourlyEquivalent(w):undefined;return <span key={c.id}>{w&&hourly!=null?`${formatMoney(hourly,w.currency)}/h`:w?.headline??'—'}</span>})}</div><div className="compare-row"><span>Equiv. mensal</span>{chosen.map(c=>{const w=wage(c.id);const monthly=w?monthlyEquivalent(w):undefined;return <span key={c.id}>{w&&monthly!=null?`${formatMoney(monthly,w.currency)}/mês`:w?.headline??'—'}</span>})}</div><div className="compare-row"><span>≈ em reais</span>{chosen.map(c=>{const w=wage(c.id);const monthly=w?monthlyEquivalent(w):undefined;const brl=w?convertNativeToBRL(monthly,w.currency,fx.rates):undefined;return <span key={c.id}>{brl!=null?formatBRL(brl):'—'}</span>})}</div><div className="compare-row"><span>Pontos positivos</span>{chosen.map(c=><span key={c.id}>{c.pros.slice(0,3).join(' • ')}</span>)}</div><div className="compare-row"><span>Pontos de atenção</span>{chosen.map(c=><span key={c.id}>{c.cons.slice(0,3).join(' • ')}</span>)}</div></div><small>Pisos são valores brutos e não equivalem ao salário médio de uma carreira. Custos, impostos e imigração só devem ganhar números quando houver fonte/data confiável.</small></section>
      <section className="glass-panel content-panel"><h2>4. Dê sua nota pessoal</h2><p>De 1 a 5 para cada critério. Se você ainda não pesquisou algo, deixe sem nota.</p><div className="rating-table"><div className="rating-head"><span>Critério</span>{chosen.map(c=><strong key={c.id}>{c.flag} {c.name}</strong>)}</div>{criteria.map(([key,label])=><div className="rating-row" key={key}><span>{label}</span>{chosen.map(c=><select key={c.id} aria-label={`${label} para ${c.name}`} value={ratings[c.id]?.[key]??''} onChange={e=>setRating(c.id,key,Number(e.target.value))}><option value="">—</option>{[1,2,3,4,5].map(n=><option value={n} key={n}>{n}/5</option>)}</select>)}</div>)}</div></section>
      <section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Resultado pessoal</span><h2>Compatibilidade segundo suas notas</h2></div></div><div className="personal-ranking">{ranking.map((c,i)=><article key={c.id}><span className="rank-position">{i+1}</span><span className="flag">{c.flag}</span><div><strong>{c.name}</strong><div className="progress-line"><span style={{width:`${score(c.id)}%`}}/></div><small>{score(c.id)}% com as notas atuais</small></div><Link className="text-link" to={`/countries/${c.id}`}>Abrir →</Link></article>)}</div><div className="warning-box">🟠 Isso não diz qual país é “melhor”. É só uma ferramenta de organização baseada nas notas que você mesmo deu.</div></section></>}
  </div>
}
