import { useEffect } from 'react'
import { ArrowLeft, ExternalLink, Heart, Map, MapPin, ShieldCheck, TriangleAlert } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { countries } from '../data/countries'
import { countryCurrent } from '../data/countryCurrent'
import { CountryOccupationSalaries } from '../components/CountryOccupationSalaries'
import { WagePanel } from '../components/WagePanel'
import { useCountryFacts } from '../hooks/useCountryFacts'
import { useAppState } from '../hooks/useAppState'

const slug=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const immigrationPath=[['Turismo','Entrada temporária conforme nacionalidade e regra vigente'],['Estudo','Curso, instituição, recursos e permissão adequada'],['Trabalho','Oferta/qualificação e autorização conforme o sistema local'],['Residência','Manter status legal e cumprir condições'],['Longo prazo','Alguns países têm residência permanente ou equivalente'],['Cidadania','Pode existir depois de requisitos legais; nunca é automática']]
const documentChecklist=['Passaporte válido','Permissão/visto quando exigido','Seguro quando obrigatório ou recomendado','Comprovação financeira quando exigida','Documentos escolares/profissionais','Traduções/certificações quando exigidas','Currículo no formato local','Comprovantes de endereço e contratos após chegada']

export function CountryPage(){
  const {id}=useParams(); const c=countries.find(x=>x.id===id); const {data,toggleFavorite,recordRecent,markCountryResearched,toggleVisitedCountry}=useAppState(); const {facts,loading,error}=useCountryFacts(c?.id)
  useEffect(()=>{if(!c)return;markCountryResearched(c.id);recordRecent({id:c.id,type:'country',title:c.name,path:`/countries/${c.id}`})},[c?.id])
  if(!c)return <div className="page"><h1>País não encontrado</h1><Link to="/countries">Voltar aos países</Link></div>
  const favId=`country:${c.id}`; const fav=data.favorites.includes(favId); const verified=countryCurrent[c.id]; const visited=data.visitedCountries.includes(c.id)
  return <div className="page country-detail-page"><nav className="breadcrumbs"><Link to="/">Início</Link><span>›</span><Link to="/countries">Países</Link><span>›</span><span>{c.name}</span></nav><section className="country-hero glass-panel"><div className="giant-flag">{c.flag}</div><div><span className="eyebrow">{c.region}</span><h1>{c.name}</h1><p>{c.capital} • {c.currency}</p><div className="tags">{c.languages.map(x=><span key={x}>{x}</span>)}</div></div><div className="country-hero-actions"><button className="icon-button big" onClick={()=>toggleFavorite(favId)} aria-label="Favoritar país"><Heart fill={fav?'currentColor':'none'}/></button><button className={visited?'chip selected':'chip'} onClick={()=>toggleVisitedCountry(c.id)}><MapPin size={14}/>{visited?'Visitado':'Marcar visitado'}</button></div></section>
    <div className="split-grid"><section className="glass-panel content-panel"><div className="section-heading"><h2>Visão geral</h2>{loading&&<span className="pill">atualizando fatos…</span>}</div><dl className="facts"><div><dt>Capital</dt><dd>{c.capital}</dd></div><div><dt>Moeda</dt><dd>{c.currency}</dd></div><div><dt>Idioma(s)</dt><dd>{c.languages.join(', ')}</dd></div><div><dt>Clima</dt><dd>{c.climate}</dd></div>{facts?.population!=null&&<div><dt>População</dt><dd>{facts.population.toLocaleString('pt-BR')}</dd></div>}{facts?.areaKm2!=null&&<div><dt>Área</dt><dd>{facts.areaKm2.toLocaleString('pt-BR')} km²</dd></div>}{facts?.timezones.length?<div><dt>Fusos</dt><dd>{facts.timezones.slice(0,4).join(', ')}{facts.timezones.length>4?'…':''}</dd></div>:null}</dl>{error&&<small>{error}</small>}{facts&&<div className="source-badge"><span>Fonte dos fatos geográficos: {facts.source}</span><time>{new Date(facts.updatedAt).toLocaleDateString('pt-BR')}</time></div>}{facts?.mapsUrl&&<a className="source-link" href={facts.mapsUrl} target="_blank" rel="noreferrer"><Map size={15}/> Abrir mapa externo<ExternalLink size={13}/></a>}</section><section className="glass-panel content-panel"><h2>Para quem pode fazer sentido</h2><ul>{c.bestFor.map(x=><li key={x}>👍 {x}</li>)}</ul><h3>Pode ser mais difícil para quem...</h3><ul>{c.harderFor.map(x=><li key={x}>• {x}</li>)}</ul><small>Esses itens são contexto geral, não um ranking absoluto.</small></section></div>
    <section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Cidades</span><h2>Pesquise a cidade, não só o país</h2></div><Link className="text-link" to={`/cities?country=${c.id}`}>Ver em lista →</Link></div><div className="city-link-grid">{c.cities.map(city=><Link className="city-mini-card" to={`/cities/${c.id}/${slug(city)}`} key={city}><span>🏙️</span><div><strong>{city}</strong><small>custo, salário e checklist</small></div></Link>)}</div></section>
    <div className="split-grid"><section className="glass-panel content-panel good"><h2><ShieldCheck/> Pontos positivos</h2>{c.pros.map(x=><p key={x}>• {x}</p>)}</section><section className="glass-panel content-panel caution"><h2><TriangleAlert/> Pontos de atenção</h2>{c.cons.map(x=><p key={x}>• {x}</p>)}</section></div>
    <WagePanel countryId={c.id}/><CountryOccupationSalaries countryId={c.id}/>
    {verified?<section className="glass-panel dynamic-data verified-data"><div className="section-heading"><div><span className="eyebrow">Dados verificados</span><h2>Estudo, trabalho e imigração</h2></div><span className="pill">Atualizado {verified.updatedAt.split('-').reverse().join('/')}</span></div><div className="split-grid"><div><h3>🎓 Estudar e trabalhar</h3>{verified.studyWork?.map(x=><p key={x}>• {x}</p>)}</div><div><h3>🛂 Imigração e permissões</h3>{verified.immigrationHighlights?.map(x=><p key={x}>• {x}</p>)}</div></div><div className="source-list"><h3>Fontes oficiais</h3>{verified.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.label}<ExternalLink size={14}/></a>)}</div><small>Regras e valores podem mudar. Confirme novamente nas fontes oficiais antes de tomar decisões.</small></section>:<section className="glass-panel dynamic-data"><h2>Estudo, trabalho e imigração</h2><p>{c.dynamicNote}</p><div className="placeholder-grid"><div><strong>🎓 Estudo</strong><span>Escolha instituição/curso e confira elegibilidade em fonte oficial.</span></div><div><strong>💼 Trabalho</strong><span>Pesquise autorização, profissão e cidade; não presuma que estudar dá direito irrestrito a trabalhar.</span></div><div><strong>🛂 Residência</strong><span>Regras atuais ainda não foram cadastradas com uma fonte específica para este país.</span></div><div><strong>🏛️ Cidadania</strong><span>Verificar naturalização, residência exigida e exceções em fonte oficial.</span></div></div><div className="warning-box">🟠 Informação migratória ainda não verificada em detalhe para este país. O site prefere mostrar a lacuna a inventar uma regra.</div></section>}
    <section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Caminho migratório</span><h2>Estrutura de pesquisa</h2></div></div><div className="immigration-timeline">{immigrationPath.map(([title,desc],i)=><article key={title}><span>{i+1}</span><div><strong>{title}</strong><small>{desc}</small></div></article>)}</div><small>Esse fluxo é uma estrutura para organizar pesquisa. Cada país pode pular, combinar ou impedir etapas dependendo da permissão.</small></section>
    <section className="glass-panel content-panel"><h2>📄 Documentos para pesquisar</h2><div className="checklist-grid static-checklist">{documentChecklist.map(item=><label className="check-item" key={item}><input type="checkbox"/> {item}</label>)}</div><small>Checklist local desta página: marque enquanto pesquisa. Para guardar o plano de mudança geral, use “Meu Futuro”.</small></section>
    <section className="glass-panel country-next-actions"><Link className="secondary-button" to="/country-compare">Comparar com outros países</Link><Link className="secondary-button" to="/world-map">Ver no mapa mundial</Link><Link className="secondary-button" to="/salaries">Comparar salários</Link></section><Link className="back-link" to="/countries"><ArrowLeft size={18}/> voltar aos países</Link>
  </div>
}
