import { useMemo, useState } from 'react'
import { BookOpen, Ear, Eye, EyeOff, Mic, PencilLine, Play, RotateCcw, Volume2 } from 'lucide-react'
import { listeningItems, readingItems, speakingItems, vocabularyItems, writingItems } from '../data/englishLab'
import { useAppState } from '../hooks/useAppState'

type Tab='listening'|'speaking'|'reading'|'writing'|'vocabulary'
interface RecognitionEventLike { results: ArrayLike<{ 0:{ transcript:string } }> }
interface RecognitionLike { lang:string; interimResults:boolean; continuous:boolean; onresult:((event:RecognitionEventLike)=>void)|null; onerror:(()=>void)|null; onend:(()=>void)|null; start:()=>void; stop:()=>void }
type RecognitionCtor = new () => RecognitionLike
const speechCtor=()=>((window as typeof window & {webkitSpeechRecognition?:RecognitionCtor;SpeechRecognition?:RecognitionCtor}).SpeechRecognition ?? (window as typeof window & {webkitSpeechRecognition?:RecognitionCtor}).webkitSpeechRecognition)

function speak(text:string,rate=1){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-US';utterance.rate=rate;window.speechSynthesis.speak(utterance)}

export function EnglishLabPage(){
 const {data,saveNote,reviewFlashcard,recordRecent}=useAppState(); const [tab,setTab]=useState<Tab>('listening'); const [listenIndex,setListenIndex]=useState(0); const [showTranscript,setShowTranscript]=useState(false); const [listenChoice,setListenChoice]=useState<number>(); const [speakingIndex,setSpeakingIndex]=useState(0); const [heard,setHeard]=useState(''); const [listening,setListening]=useState(false); const [readingIndex,setReadingIndex]=useState(0); const [writingIndex,setWritingIndex]=useState(0); const [theme,setTheme]=useState('all'); const [level,setLevel]=useState('all')
 const currentListening=listeningItems[listenIndex]; const currentSpeaking=speakingItems[speakingIndex]; const currentReading=readingItems[readingIndex]; const currentWriting=writingItems[writingIndex]
 const vocab=useMemo(()=>vocabularyItems.filter(item=>(theme==='all'||item.theme===theme)&&(level==='all'||item.level===level)),[theme,level]); const themes=[...new Set(vocabularyItems.map(x=>x.theme))];const levels=[...new Set(vocabularyItems.map(x=>x.level))]
 const startRecognition=()=>{const Ctor=speechCtor();if(!Ctor){setHeard('Reconhecimento de voz não está disponível neste navegador. Você ainda pode praticar em voz alta e comparar com o exemplo.');return}const recognition=new Ctor();recognition.lang='en-US';recognition.interimResults=false;recognition.continuous=false;recognition.onresult=event=>{setHeard(event.results[0][0].transcript);setListening(false)};recognition.onerror=()=>setListening(false);recognition.onend=()=>setListening(false);setListening(true);recognition.start()}
 const selectTab=(next:Tab)=>{setTab(next);recordRecent({id:`english-lab:${next}`,type:'english-lab',title:`Laboratório de inglês — ${next}`,path:'/english-lab'})}
 return <div className="page english-lab-page"><section className="page-header glass-panel"><div className="mega-icon">🇬🇧</div><div><span className="eyebrow">Inglês na vida real</span><h1>Laboratório de inglês</h1><p>Ouça, fale, leia, escreva e revise vocabulário em situações que realmente aparecem no cotidiano, no trabalho e ao morar fora.</p></div></section>
 <div className="lab-tabs glass-panel">{([['listening','🎧 Listening'],['speaking','🎤 Speaking'],['reading','📖 Reading'],['writing','✍️ Writing'],['vocabulary','🧠 Vocabulário']] as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>selectTab(id)}>{label}</button>)}</div>
 {tab==='listening'&&<section className="glass-panel content-panel" data-resume-section="listening"><div className="section-heading"><div><span className="eyebrow"><Ear size={15}/> {currentListening.level} • {currentListening.situation}</span><h2>Escute antes de ler</h2></div><span>{listenIndex+1}/{listeningItems.length}</span></div><div className="button-row"><button className="primary-button" onClick={()=>speak(currentListening.text,1)}><Play size={17}/> Ouvir</button><button className="secondary-button" onClick={()=>speak(currentListening.text,.7)}>🐢 Mais devagar</button><button className="secondary-button" onClick={()=>setShowTranscript(v=>!v)}>{showTranscript?<EyeOff size={17}/>:<Eye size={17}/>} {showTranscript?'Esconder texto':'Mostrar texto'}</button></div>{showTranscript&&<div className="transcript-box"><p lang="en">{currentListening.text}</p><small>{currentListening.translation}</small></div>}<h3>{currentListening.question}</h3><div className="quiz-options">{currentListening.options.map((option,index)=><button key={option} onClick={()=>setListenChoice(index)} className={listenChoice===undefined?'':index===currentListening.answer?'correct':listenChoice===index?'wrong':''}>{option}</button>)}</div>{listenChoice!==undefined&&<div className={listenChoice===currentListening.answer?'feedback ok':'feedback bad'}>{listenChoice===currentListening.answer?'Acertou ✅':'Quase. Ouça novamente e repare nas palavras-chave.'}</div>}<div className="button-row"><button className="secondary-button" onClick={()=>{setListenIndex(v=>(v-1+listeningItems.length)%listeningItems.length);setListenChoice(undefined);setShowTranscript(false)}}>← Anterior</button><button className="secondary-button" onClick={()=>{setListenIndex(v=>(v+1)%listeningItems.length);setListenChoice(undefined);setShowTranscript(false)}}>Próximo →</button></div></section>}
 {tab==='speaking'&&<section className="glass-panel content-panel" data-resume-section="speaking"><div className="section-heading"><div><span className="eyebrow"><Mic size={15}/> {currentSpeaking.level} • {currentSpeaking.situation}</span><h2>{currentSpeaking.prompt}</h2></div><span>{speakingIndex+1}/{speakingItems.length}</span></div><div className="chip-row">{currentSpeaking.useful.map(x=><span className="chip static" key={x}>{x}</span>)}</div><div className="example-box"><strong>Exemplo possível</strong><p lang="en">{currentSpeaking.example}</p><button className="text-button" onClick={()=>speak(currentSpeaking.example,.88)}><Volume2 size={16}/> Ouvir exemplo</button></div><button className="primary-button" disabled={listening} onClick={startRecognition}><Mic size={18}/> {listening?'Ouvindo…':'Responder em voz alta'}</button>{heard&&<div className="transcript-box"><strong>O navegador entendeu:</strong><p lang="en">{heard}</p><small>Use isso só como apoio. O objetivo é ser compreendido, não “zerar sotaque”.</small></div>}<label>Minha anotação / resposta<input value={data.notes[`speaking:${currentSpeaking.id}`]??''} onChange={e=>saveNote(`speaking:${currentSpeaking.id}`,e.target.value)} placeholder="Você também pode escrever sua resposta aqui."/></label><div className="button-row"><button className="secondary-button" onClick={()=>{setSpeakingIndex(v=>(v-1+speakingItems.length)%speakingItems.length);setHeard('')}}>← Anterior</button><button className="secondary-button" onClick={()=>{setSpeakingIndex(v=>(v+1)%speakingItems.length);setHeard('')}}>Próximo →</button></div></section>}
 {tab==='reading'&&<section className="glass-panel content-panel reading-lab" data-resume-section="reading"><div className="section-heading"><div><span className="eyebrow"><BookOpen size={15}/> {currentReading.level}</span><h2>{currentReading.title}</h2></div><span>{readingIndex+1}/{readingItems.length}</span></div><article className="reading-text"><p>{currentReading.text}</p></article><h3>Vocabulário útil</h3><div className="vocab-mini-grid">{currentReading.vocabulary.map(([word,meaning])=><button key={word} onClick={()=>speak(word,.85)}><strong>{word}</strong><span>{meaning}</span><Volume2 size={14}/></button>)}</div><h3>Perguntas para conferir entendimento</h3>{currentReading.questions.map((q,i)=><div className="example-box" key={q}><strong>{i+1}.</strong> {q}</div>)}<div className="button-row"><button className="secondary-button" onClick={()=>setReadingIndex(v=>(v-1+readingItems.length)%readingItems.length)}>← Anterior</button><button className="secondary-button" onClick={()=>setReadingIndex(v=>(v+1)%readingItems.length)}>Próximo →</button></div></section>}
 {tab==='writing'&&<section className="glass-panel content-panel" data-resume-section="writing"><div className="section-heading"><div><span className="eyebrow"><PencilLine size={15}/> {currentWriting.level}</span><h2>{currentWriting.title}</h2></div><span>{writingIndex+1}/{writingItems.length}</span></div><p>{currentWriting.prompt}</p><div className="checklist-grid">{currentWriting.checklist.map(item=><div className="check-item" key={item}>☐ {item}</div>)}</div><div className="example-box"><strong>Começo possível</strong><p lang="en">{currentWriting.exampleStart}</p></div><label>Minha resposta<textarea rows={10} value={data.notes[`writing:${currentWriting.id}`]??''} onChange={e=>saveNote(`writing:${currentWriting.id}`,e.target.value)} placeholder="Escreva aqui. O texto salva automaticamente."/></label><small>💾 Salvo automaticamente no seu progresso e sincronizado quando sua conta estiver conectada.</small><div className="button-row"><button className="secondary-button" onClick={()=>setWritingIndex(v=>(v-1+writingItems.length)%writingItems.length)}>← Anterior</button><button className="secondary-button" onClick={()=>setWritingIndex(v=>(v+1)%writingItems.length)}>Próximo →</button></div></section>}
 {tab==='vocabulary'&&<section className="glass-panel content-panel" data-resume-section="vocabulary"><div className="section-heading"><div><span className="eyebrow"><RotateCcw size={15}/> Vocabulário por tema</span><h2>{vocabularyItems.length} palavras e expressões iniciais</h2></div></div><div className="search-filter-grid"><label>Tema<select value={theme} onChange={e=>setTheme(e.target.value)}><option value="all">Todos</option>{themes.map(x=><option key={x}>{x}</option>)}</select></label><label>Nível<select value={level} onChange={e=>setLevel(e.target.value)}><option value="all">Todos</option>{levels.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="vocabulary-grid">{vocab.map(item=>{const review=data.flashcardReviews[`vocabulary:${item.id}`];return <article className="glass-panel vocab-card" key={item.id}><div className="card-top"><span className="pill">{item.level} • {item.theme}</span>{item.register&&item.register!=='neutral'&&<span className="pill">{item.register==='slang'?'gíria':item.register}</span>}</div><h3>{item.word}</h3><p>{item.meaning}</p><div className="example-box">{item.example}</div><div className="button-row"><button className="icon-button" onClick={()=>speak(item.word,.82)} aria-label={`Ouvir ${item.word}`}><Volume2 size={17}/></button><button onClick={()=>reviewFlashcard(`vocabulary:${item.id}`,'hard')}>😕</button><button onClick={()=>reviewFlashcard(`vocabulary:${item.id}`,'normal')}>🙂</button><button onClick={()=>reviewFlashcard(`vocabulary:${item.id}`,'easy')}>😎</button></div>{review&&<small>Próxima revisão: {new Date(review.nextReviewAt).toLocaleDateString('pt-BR')}</small>}</article>})}</div></section>}
 </div>
}
