import { useMemo, useState } from 'react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Plus, Trash2, WalletCards } from 'lucide-react'
import { useAppState } from '../hooks/useAppState'

const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})

export function FinancialPlannerPage(){
 const {data,updateFinancialPlan,addFinancialHistory,removeFinancialHistory}=useAppState(); const plan=data.financialPlan
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7)); const [netWorth,setNetWorth]=useState(plan.savedAmount)
 const balance=plan.monthlyIncome-plan.fixedExpenses-plan.variableExpenses; const saveRate=plan.monthlyIncome>0?Math.max(0,balance/plan.monthlyIncome*100):0; const remaining=Math.max(0,plan.goalAmount-plan.savedAmount); const contribution=plan.monthlyContribution>0?plan.monthlyContribution:Math.max(0,balance); const months=contribution>0?Math.ceil(remaining/contribution):null
 const projection=useMemo(()=>{const rows=[];let value=plan.savedAmount;for(let i=0;i<=Math.min(months??12,60);i++){rows.push({month:i,value});value+=contribution}return rows},[plan.savedAmount,contribution,months])
 const history=[...data.financialHistory].sort((a,b)=>a.month.localeCompare(b.month))
 return <div className="page financial-page"><section className="page-header glass-panel"><WalletCards className="mega-icon-svg"/><div><span className="eyebrow">Planejamento financeiro</span><h1>Seu dinheiro com uma função clara.</h1><p>Registre renda, gastos, dinheiro guardado e uma meta. Os dados ficam no navegador e entram na sincronização da conta.</p></div></section>
 <section className="stats-grid"><article className="stat-card glass-panel"><div><strong>{money(balance)}</strong><span>saldo mensal estimado</span></div></article><article className="stat-card glass-panel"><div><strong>{saveRate.toFixed(0)}%</strong><span>taxa de economia</span></div></article><article className="stat-card glass-panel"><div><strong>{money(remaining)}</strong><span>falta para {plan.goalName||'a meta'}</span></div></article><article className="stat-card glass-panel"><div><strong>{months??'—'}</strong><span>meses estimados sem rendimento</span></div></article></section>
 <div className="split-grid"><section className="glass-panel content-panel"><h2>Meu mês</h2><label>Renda mensal<input type="number" min="0" value={plan.monthlyIncome} onChange={e=>updateFinancialPlan({monthlyIncome:Number(e.target.value)})}/></label><label>Gastos fixos<input type="number" min="0" value={plan.fixedExpenses} onChange={e=>updateFinancialPlan({fixedExpenses:Number(e.target.value)})}/></label><label>Gastos variáveis<input type="number" min="0" value={plan.variableExpenses} onChange={e=>updateFinancialPlan({variableExpenses:Number(e.target.value)})}/></label><div className="example-box">Renda − gastos fixos − gastos variáveis = <strong>{money(balance)}</strong></div></section><section className="glass-panel content-panel"><h2>Minha meta</h2><label>Nome da meta<input value={plan.goalName} onChange={e=>updateFinancialPlan({goalName:e.target.value})} placeholder="Ex.: Irlanda"/></label><label>Valor da meta<input type="number" min="0" value={plan.goalAmount} onChange={e=>updateFinancialPlan({goalAmount:Number(e.target.value)})}/></label><label>Já guardado<input type="number" min="0" value={plan.savedAmount} onChange={e=>updateFinancialPlan({savedAmount:Number(e.target.value)})}/></label><label>Aporte mensal planejado<input type="number" min="0" value={plan.monthlyContribution} onChange={e=>updateFinancialPlan({monthlyContribution:Number(e.target.value)})}/></label><div className="progress-line"><span style={{width:`${plan.goalAmount>0?Math.min(100,plan.savedAmount/plan.goalAmount*100):0}%`}}/></div><small>{plan.goalAmount>0?Math.min(100,plan.savedAmount/plan.goalAmount*100).toFixed(0):0}% da meta.</small></section></div>
 <section className="glass-panel chart-panel"><div className="section-heading"><div><span className="eyebrow">Projeção simples</span><h2>Se você mantiver {money(contribution)} por mês</h2></div></div><ResponsiveContainer width="100%" height={300}><AreaChart data={projection}><CartesianGrid strokeDasharray="3 3" opacity={.14}/><XAxis dataKey="month" tickFormatter={v=>`${v}m`}/><YAxis tickFormatter={v=>`R$${Math.round(v/1000)}k`}/><Tooltip formatter={(value)=>money(Number(value))}/><Area type="monotone" dataKey="value" stroke="var(--primary)" fill="var(--primary)" fillOpacity={.2}/></AreaChart></ResponsiveContainer><small>Estimativa educativa sem considerar rendimento, inflação, impostos ou mudanças nos aportes.</small></section>
 <section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Patrimônio</span><h2>Histórico mensal</h2></div></div><div className="form-row"><label>Mês<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label>Patrimônio<input type="number" min="0" value={netWorth} onChange={e=>setNetWorth(Number(e.target.value))}/></label><button className="primary-button" onClick={()=>addFinancialHistory({id:`networth:${month}`,month,netWorth,savedAmount:plan.savedAmount,createdAt:new Date().toISOString()})}><Plus size={17}/> Salvar mês</button></div>{history.length>0&&<><ResponsiveContainer width="100%" height={280}><AreaChart data={history}><CartesianGrid strokeDasharray="3 3" opacity={.14}/><XAxis dataKey="month"/><YAxis tickFormatter={v=>`R$${Math.round(v/1000)}k`}/><Tooltip formatter={(value)=>money(Number(value))}/><Area type="monotone" dataKey="netWorth" stroke="var(--secondary)" fill="var(--secondary)" fillOpacity={.22}/></AreaChart></ResponsiveContainer><div className="history-list">{history.map(item=><div key={item.id}><span>{item.month}</span><strong>{money(item.netWorth)}</strong><button className="icon-button" aria-label="Excluir registro" onClick={()=>removeFinancialHistory(item.id)}><Trash2 size={15}/></button></div>)}</div></>}</section>
 <section className="glass-panel content-panel"><h2>💡 Regra útil</h2><p>Reserva de emergência e dinheiro de objetivo podem ter funções diferentes. Não misture automaticamente tudo em uma única meta só porque aparece no mesmo gráfico.</p></section></div>
}
