import { useMemo, useState } from 'react'
import { BriefcaseBusiness, CalendarClock, Plus, Target, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { careers } from '../data/careers'
import { occupationWagesForCareer } from '../data/occupationWages'
import { useAppState } from '../hooks/useAppState'
import type { Priority } from '../types'

const relocationSteps=['Inglês','Dinheiro','País','Passaporte','Curso','Visto','Documentos','Trabalho','Moradia','Passagem','Seguro','Banco','Chip','Transporte','Primeiros dias']
const relocationTimeline=[['Planejamento','Metas, país e prazo'],['Idioma','Inglês ou idioma local'],['Dinheiro','Reserva e custo inicial'],['Documentos','Passaporte, curso e vistos'],['Viagem','Passagem, seguro e chegada'],['Estudo','Idioma, técnico ou faculdade'],['Trabalho','Permissão e busca de emprego'],['Residência','Manter status legal'],['Longo prazo','Residência permanente quando existir'],['Cidadania','Possibilidade futura, nunca garantia']]

export function FuturePage(){
  const {data,updateGoal,addGoal,removeGoal,toggleGoalSubtask,toggleRelocationStep}=useAppState()
  const [title,setTitle]=useState(''); const [target,setTarget]=useState(100); const [unit,setUnit]=useState('%'); const [deadline,setDeadline]=useState(''); const [priority,setPriority]=useState<Priority>('normal'); const [careerId,setCareerId]=useState(careers[0].id)
  const relocationDone=relocationSteps.filter(x=>data.relocationChecklist[x]).length
  const career=careers.find(c=>c.id===careerId)??careers[0]
  const salaryRefs=useMemo(()=>occupationWagesForCareer(career.id),[career.id])
  const addSubtask=(goalId:string)=>{const text=prompt('Qual é a próxima tarefa pequena?')?.trim();if(!text)return;const goal=data.goals.find(g=>g.id===goalId);if(!goal)return;updateGoal({...goal,subtasks:[...(goal.subtasks??[]),{id:`sub-${Date.now()}`,title:text,done:false}]})}
  const updateSubtaskText=(goalId:string,subId:string,title:string)=>{const goal=data.goals.find(g=>g.id===goalId);if(!goal)return;updateGoal({...goal,subtasks:(goal.subtasks??[]).map(s=>s.id===subId?{...s,title}:s)})}
  return <div className="page future-page">
    <section className="page-header glass-panel"><Target className="mega-icon-svg"/><div><span className="eyebrow">Planejamento pessoal</span><h1>Meu Futuro</h1><p>Transforme objetivos grandes em passos menores: estudo, carreira, dinheiro, país e documentos.</p></div></section>

    <section className="goal-grid">{data.goals.map(g=>{const pct=g.target>0?Math.min(100,Math.round(g.current/g.target*100)):0;const tasks=g.subtasks??[];return <article className="goal-card glass-panel" key={g.id}><div className="card-top"><span className={`pill priority-${g.priority??'normal'}`}>{g.priority==='high'?'Alta prioridade':g.priority==='low'?'Baixa prioridade':'Prioridade normal'}</span><button className="icon-button" onClick={()=>confirm(`Excluir a meta “${g.title}”?`)&&removeGoal(g.id)} aria-label="Excluir meta"><Trash2 size={17}/></button></div><h3>{g.title}</h3><div className="progress-line"><span style={{width:`${pct}%`}}/></div><div className="goal-numbers"><span>{g.unit==='R$'?`R$ ${g.current.toLocaleString('pt-BR')}`:`${g.current}${g.unit}`}</span><strong>{pct}%</strong><span>de {g.unit==='R$'?`R$ ${g.target.toLocaleString('pt-BR')}`:`${g.target}${g.unit}`}</span></div><div className="goal-edit-grid"><label>Atual<input type="number" value={g.current} onChange={e=>updateGoal({...g,current:Number(e.target.value)})}/></label><label>Prazo<input type="date" value={g.deadline??''} onChange={e=>updateGoal({...g,deadline:e.target.value})}/></label><label>Prioridade<select value={g.priority??'normal'} onChange={e=>updateGoal({...g,priority:e.target.value as Priority})}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option></select></label></div><label>Notas<textarea value={g.notes??''} onChange={e=>updateGoal({...g,notes:e.target.value})} placeholder="Por que essa meta importa? O que falta decidir?"/></label><div className="goal-subtasks"><div className="card-top"><strong>Subtarefas</strong><button className="text-button" onClick={()=>addSubtask(g.id)}><Plus size={14}/> adicionar</button></div>{tasks.length===0?<small>Nenhuma subtarefa ainda.</small>:tasks.map(task=><label className="subtask-row" key={task.id}><input type="checkbox" checked={task.done} onChange={()=>toggleGoalSubtask(g.id,task.id)}/><input value={task.title} onChange={e=>updateSubtaskText(g.id,task.id,e.target.value)}/></label>)}</div></article>})}</section>

    <section className="glass-panel content-panel"><h2>Adicionar meta</h2><div className="goal-create-grid"><label>Nome<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Criar 10 projetos"/></label><label>Valor alvo<input type="number" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label><label>Unidade<select value={unit} onChange={e=>setUnit(e.target.value)}><option value="%">%</option><option value="R$">R$</option><option value=" projetos">projetos</option><option value=" aulas">aulas</option><option value=" países">países</option><option value=" horas">horas</option></select></label><label>Prazo<input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><label>Prioridade<select value={priority} onChange={e=>setPriority(e.target.value as Priority)}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option></select></label><button className="primary-button" onClick={()=>{if(!title.trim()||target<=0)return;addGoal({id:`goal-${Date.now()}`,title:title.trim(),target,current:0,unit,deadline:deadline||undefined,priority,subtasks:[]});setTitle('');setDeadline('')}}><Plus size={18}/> Adicionar</button></div></section>

    <section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Mudança para o exterior</span><h2>Checklist — {relocationDone}/{relocationSteps.length}</h2></div><strong>{Math.round(relocationDone/relocationSteps.length*100)}%</strong></div><div className="progress-line"><span style={{width:`${relocationDone/relocationSteps.length*100}%`}}/></div><div className="checklist-grid">{relocationSteps.map(x=><label className="check-item" key={x}><input type="checkbox" checked={!!data.relocationChecklist[x]} onChange={()=>toggleRelocationStep(x)}/> {x}</label>)}</div></section>

    <section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow"><CalendarClock size={15}/> Linha do tempo</span><h2>Do plano à possibilidade de cidadania</h2></div></div><div className="relocation-timeline">{relocationTimeline.map(([title,desc],i)=><article key={title}><span>{i+1}</span><div><strong>{title}</strong><small>{desc}</small></div></article>)}</div><small>Os últimos passos dependem das leis do país, do tipo de permissão e do seu histórico de residência. A linha é um mapa de planejamento, não uma promessa migratória.</small></section>

    <section className="glass-panel content-panel career-planner"><div className="section-heading"><div><span className="eyebrow"><BriefcaseBusiness size={15}/> Planejador de carreira</span><h2>Escolha uma direção e transforme em estudo</h2></div><Link className="text-link" to="/careers">Explorar todas →</Link></div><label>Carreira desejada<select value={careerId} onChange={e=>setCareerId(e.target.value)}>{careers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="career-plan-grid"><article><span className="career-plan-icon">{career.icon}</span><h3>{career.name}</h3><p>{career.summary}</p><strong>Habilidades</strong><div className="tags">{career.skills.map(x=><span key={x}>{x}</span>)}</div></article><article><h3>Roadmap sugerido</h3><ol className="roadmap compact-roadmap">{career.roadmap.map((x,i)=><li key={x}><span>{i+1}</span>{x}</li>)}</ol></article><article><h3>Projetos de portfólio</h3>{career.portfolio.map(x=><div className="example-box" key={x}>{x}</div>)}</article><article><h3>Referências salariais</h3>{salaryRefs.length?<><p>{salaryRefs.length} referência(s) pública(s) disponível(is) para essa carreira ou grupo ocupacional.</p><Link className="secondary-button" to={`/careers/${career.id}`}>Ver salários por país</Link></>:<p className="muted">Ainda não há uma referência salarial pública suficientemente específica cadastrada. O site não inventa um valor.</p>}</article></div></section>
  </div>
}
