import { useState } from 'react'
import { Plus, Target } from 'lucide-react'
import { useAppState } from '../hooks/useAppState'

const relocationSteps=['Inglês','Dinheiro','País','Passaporte','Curso','Visto','Documentos','Trabalho','Moradia','Passagem','Seguro','Banco','Chip','Transporte','Primeiros dias']

export function FuturePage(){
 const {data,updateGoal,addGoal,toggleRelocationStep}=useAppState(); const [title,setTitle]=useState(''); const [target,setTarget]=useState(100); const [unit,setUnit]=useState('%')
 const relocationDone=relocationSteps.filter(x=>data.relocationChecklist[x]).length
 return <div className="page"><section className="page-header glass-panel"><Target className="mega-icon-svg"/><div><span className="eyebrow">Planejamento pessoal</span><h1>Meu Futuro</h1><p>Transforme objetivos grandes em progresso visível. Seus dados ficam salvos neste navegador.</p></div></section><div className="goal-grid">{data.goals.map(g=>{const pct=g.target>0?Math.min(100,Math.round(g.current/g.target*100)):0;return <article className="goal-card glass-panel" key={g.id}><div className="card-top"><span className="pill">Meta</span><strong>{pct}%</strong></div><h3>{g.title}</h3><div className="progress-line"><span style={{width:`${pct}%`}}/></div><div className="goal-numbers"><span>{g.unit==='R$'?`R$ ${g.current.toLocaleString('pt-BR')}`:`${g.current}${g.unit}`}</span><span>de {g.unit==='R$'?`R$ ${g.target.toLocaleString('pt-BR')}`:`${g.target}${g.unit}`}</span></div><label>Atualizar progresso<input type="number" value={g.current} onChange={e=>updateGoal({...g,current:Number(e.target.value)})}/></label></article>})}</div><section className="glass-panel content-panel"><h2>Adicionar meta</h2><div className="form-row"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Criar 10 projetos"/><input aria-label="Valor da meta" type="number" value={target} onChange={e=>setTarget(Number(e.target.value))}/><select aria-label="Unidade" value={unit} onChange={e=>setUnit(e.target.value)}><option value="%">%</option><option value="R$">R$</option><option value=" projetos">projetos</option><option value=" aulas">aulas</option><option value=" países">países</option></select><button className="primary-button" onClick={()=>{if(!title.trim()||target<=0)return;addGoal({id:`goal-${Date.now()}`,title:title.trim(),target,current:0,unit});setTitle('')}}><Plus size={18}/> Adicionar</button></div><div className="section-heading"><div><span className="eyebrow">Mudança para o exterior</span><h3>Checklist — {relocationDone}/{relocationSteps.length}</h3></div><strong>{Math.round(relocationDone/relocationSteps.length*100)}%</strong></div><div className="progress-line"><span style={{width:`${relocationDone/relocationSteps.length*100}%`}}/></div><div className="checklist-grid">{relocationSteps.map(x=><label className="check-item" key={x}><input type="checkbox" checked={!!data.relocationChecklist[x]} onChange={()=>toggleRelocationStep(x)}/> {x}</label>)}</div></section></div>
}
