import { ArrowRight, BookOpenCheck, Brain, CalendarDays, Code2, Flame, ListChecks, Sparkles, Target, Timer, WalletCards, Wrench } from 'lucide-react'
import { Link } from 'react-router-dom'
import { lessons, courseMeta } from '../data/lessons'
import { flashcards, quizzes } from '../data/activities'
import { countries } from '../data/countries'
import { careers } from '../data/careers'
import { studyMetrics } from '../lib/metrics'
import { useAppState } from '../hooks/useAppState'

export function Home() {
  const { data } = useAppState(); const metrics=studyMetrics(data)
  const completed = Object.keys(data.completed).length; const pct = Math.round((completed / lessons.length) * 100)
  const perCourse = (course: keyof typeof courseMeta) => {const all=lessons.filter(x=>x.course===course);const done=all.filter(x=>data.completed[x.id]).length;return Math.round(done/all.length*100)}
  const due=lessons.filter(l=>{const c=data.completed[l.id];return c?.nextReviewAt&&new Date(c.nextReviewAt).getTime()<=Date.now()}).length
  const lastLessonRecent=data.recent.find(x=>x.type==='lesson'); const continueLesson=lastLessonRecent?lessons.find(l=>l.id===lastLessonRecent.id):lessons.find(l=>!data.completed[l.id])
  const last7=new Date(Date.now()-6*86400000);last7.setHours(0,0,0,0);const weeklySessions=data.studySessions.filter(s=>new Date(s.startedAt)>=last7).length;const weeklyTarget=5
  const preferred=data.preferences.countries.map(id=>countries.find(c=>c.id===id)).filter((x):x is NonNullable<typeof x>=>Boolean(x)).slice(0,4)
  return <div className="page page-home">
    <section className="hero-card glass-panel"><div className="eyebrow"><Sparkles size={16}/> Seu espaço pessoal de evolução</div><h1>Oi, {data.displayName || 'Estudante'} 👋</h1><p>Que tal avançar por {data.settings.defaultStudyMinutes} minutos hoje? Você escolhe o ritmo; o site cuida de deixar o próximo passo visível.</p><div className="hero-actions"><Link className="primary-button" to="/today">Estudar agora <ArrowRight size={18}/></Link><Link className="secondary-button" to="/future">Ver minhas metas <Target size={18}/></Link></div><div className="hero-orbit" aria-hidden="true"><span>🇬🇧</span><span>💰</span><span>🌍</span><span>💻</span></div></section>

    {continueLesson&&<section className="continue-card glass-panel"><div><span className="eyebrow">Continuar estudando</span><h2>{continueLesson.title}</h2><p>{continueLesson.description}</p><div className="meta-row"><span>{continueLesson.module}</span><span>{continueLesson.estimatedMinutes} min</span></div></div><Link className="primary-button" to={`/lesson/${continueLesson.id}`}>Continuar <ArrowRight size={18}/></Link></section>}

    <section className="dashboard-stats-grid"><article className="stat-card glass-panel"><Flame/><div><strong>{metrics.streak}</strong><span>dias de sequência</span></div></article><article className="stat-card glass-panel"><BookOpenCheck/><div><strong>{pct}%</strong><span>progresso geral</span></div></article><article className="stat-card glass-panel"><Timer/><div><strong>{metrics.todayMinutes}</strong><span>min hoje</span></div></article><article className="stat-card glass-panel"><Brain/><div><strong>{due}</strong><span>revisões vencidas</span></div></article></section>

    <div className="split-grid"><section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Meta semanal</span><h2>{Math.min(weeklySessions,weeklyTarget)}/{weeklyTarget} sessões</h2></div><strong>{Math.min(100,Math.round(weeklySessions/weeklyTarget*100))}%</strong></div><div className="progress-line"><span style={{width:`${Math.min(100,weeklySessions/weeklyTarget*100)}%`}}/></div><div className="mini-stats"><span>Hoje <strong>{metrics.todayMinutes} min</strong></span><span>7 dias <strong>{metrics.weeklyMinutes} min</strong></span><span>Mês <strong>{metrics.monthlyMinutes} min</strong></span><span>Total <strong>{data.studyMinutes} min</strong></span></div><Link className="text-link" to="/calendar"><CalendarDays size={16}/> Abrir calendário de estudos →</Link></section><section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Revisões</span><h2>{due?`${due} conteúdo(s) esperando`:'Tudo em dia'}</h2></div></div><p>{due?'Revisar um pouco agora evita precisar reaprender tudo depois.':'Quando uma revisão vencer, ela aparece aqui automaticamente.'}</p><Link className="secondary-button" to="/review">Abrir revisão</Link></section></div>

    <section><div className="section-heading"><div><span className="eyebrow">Trilhas</span><h2>O que você quer estudar?</h2></div></div><div className="course-grid">{(Object.keys(courseMeta) as (keyof typeof courseMeta)[]).map(key=>{const meta=courseMeta[key];return <Link key={key} to={`/course/${key}`} className={`course-card course-${key} glass-panel`}><div className="course-icon">{meta.icon}</div><h3>{meta.title}</h3><p>{meta.description}</p><div className="progress-line"><span style={{width:`${perCourse(key)}%`}}/></div><small>{perCourse(key)}% concluído</small></Link>})}<Link to="/countries" className="course-card course-countries glass-panel"><div className="course-icon">🌍</div><h3>Países</h3><p>{countries.length} países com cidades, idiomas, prós, contras e comparação.</p><span className="text-link">Explorar países →</span></Link><Link to="/careers" className="course-card course-careers glass-panel"><div className="course-icon">💼</div><h3>Carreiras</h3><p>{careers.length} carreiras com habilidades, roadmaps e portfólio.</p><span className="text-link">Ver carreiras →</span></Link></div></section>

    <section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Metas rápidas</span><h2>Seu futuro em números</h2></div><Link className="text-link" to="/future">Gerenciar metas →</Link></div><div className="quick-goals">{data.goals.slice(0,4).map(g=>{const p=g.target>0?Math.min(100,Math.round(g.current/g.target*100)):0;return <article key={g.id}><div><strong>{g.title}</strong><small>{g.unit==='R$'?`R$ ${g.current.toLocaleString('pt-BR')} de R$ ${g.target.toLocaleString('pt-BR')}`:`${g.current}${g.unit} de ${g.target}${g.unit}`}</small></div><span>{p}%</span><div className="progress-line"><i style={{width:`${p}%`}}/></div></article>})}</div></section>

    {preferred.length>0&&<section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Seus países</span><h2>Acompanhar primeiro</h2></div><Link className="text-link" to="/countries">Ver todos →</Link></div><div className="preferred-countries">{preferred.map(c=><Link key={c.id} to={`/countries/${c.id}`}><span>{c.flag}</span><strong>{c.name}</strong><small>{c.capital} • {c.currency}</small></Link>)}</div></section>}

    <section className="split-grid"><article className="glass-panel feature-card"><span className="eyebrow">📓 Modo caderno</span><h2>Conteúdo pronto para copiar.</h2><p>Cada aula tem dica bônus, frase da página, exemplo e desenho fácil.</p><Link className="text-link" to="/notebook">Abrir caderno →</Link></article><article className="glass-panel feature-card"><Brain/><span className="eyebrow">{flashcards.length} flashcards</span><h2>Revisão espaçada.</h2><p>Vire o card, ouça inglês, favorite e marque a dificuldade.</p><Link className="text-link" to="/flashcards">Abrir flashcards →</Link></article></section>
    <section className="split-grid"><article className="glass-panel feature-card"><ListChecks/><span className="eyebrow">{quizzes.length} quizzes</span><h2>Teste se entendeu mesmo.</h2><p>As respostas erradas voltam na área de revisão.</p><Link className="text-link" to="/quizzes">Fazer um quiz →</Link></article><article className="glass-panel feature-card"><WalletCards/><span className="eyebrow">Salários e câmbio</span><h2>Hora, mês e reais.</h2><p>Compare pisos, equivalentes mensais e referências por profissão quando houver fonte.</p><Link className="text-link" to="/salaries">Comparar salários →</Link></article></section>
    <section className="split-grid"><article className="glass-panel feature-card"><Code2/><span className="eyebrow">Programação prática</span><h2>Escreva e teste código.</h2><p>Playground visual e desafios automáticos com pistas.</p><div className="button-row"><Link className="text-link" to="/playground">Playground →</Link><Link className="text-link" to="/practice">Desafios →</Link></div></article><article className="glass-panel feature-card"><Wrench/><span className="eyebrow">Ferramentas</span><h2>Simule antes de decorar.</h2><p>Juros, inflação, orçamento, metas, carteira e câmbio.</p><Link className="text-link" to="/tools">Abrir ferramentas →</Link></article></section>

    <section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Visto recentemente</span><h2>Volte sem procurar tudo de novo</h2></div><Link className="text-link" to="/history">Histórico completo →</Link></div>{data.recent.length===0?<p className="muted">Seu histórico começa a aparecer conforme você navega.</p>:<div className="recent-row">{data.recent.slice(0,6).map(item=><Link to={item.path} key={`${item.type}-${item.id}`}><strong>{item.title}</strong><small>{new Date(item.viewedAt).toLocaleDateString('pt-BR')}</small></Link>)}</div>}</section>
  </div>
}
