import { useState } from 'react'
import { ExternalLink, Github, Pencil, Plus, Trash2 } from 'lucide-react'
import { useAppState } from '../hooks/useAppState'
import type { PortfolioProject } from '../types'

const blank=():PortfolioProject=>({id:`project-${Date.now()}`,name:'',description:'',technologies:[],imageUrl:'',githubUrl:'',demoUrl:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})

export function PortfolioPage(){
 const {data,savePortfolioProject,deletePortfolioProject}=useAppState(); const [draft,setDraft]=useState<PortfolioProject>(blank()); const [techText,setTechText]=useState(''); const [editing,setEditing]=useState(false)
 const startNew=()=>{setDraft(blank());setTechText('');setEditing(true)}
 const edit=(project:PortfolioProject)=>{setDraft(project);setTechText(project.technologies.join(', '));setEditing(true)}
 const save=()=>{if(!draft.name.trim())return;savePortfolioProject({...draft,name:draft.name.trim(),description:draft.description.trim(),technologies:[...new Set(techText.split(',').map(x=>x.trim()).filter(Boolean))],updatedAt:new Date().toISOString()});setEditing(false);setDraft(blank());setTechText('')}
 return <div className="page portfolio-page"><section className="page-header glass-panel"><div className="mega-icon">🧰</div><div><span className="eyebrow">Carreira em construção</span><h1>Meus projetos</h1><p>Guarde projetos que mostram o que você sabe fazer. Com login, o portfólio também acompanha você em outros dispositivos.</p></div></section><section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Portfólio</span><h2>{data.portfolioProjects.length} projeto(s)</h2></div><button className="primary-button" onClick={startNew}><Plus size={17}/> Novo projeto</button></div>{data.portfolioProjects.length===0&&!editing&&<div className="empty">Ainda não há projeto salvo. Comece com algo pequeno que funciona — calculadora, quiz, site pessoal, API ou dashboard.</div>}</section>
 {editing&&<section className="glass-panel content-panel portfolio-form"><h2>{data.portfolioProjects.some(x=>x.id===draft.id)?'Editar projeto':'Adicionar projeto'}</h2><div className="split-grid"><label>Nome<input value={draft.name} onChange={e=>setDraft(d=>({...d,name:e.target.value}))} placeholder="Ex.: Dashboard financeiro"/></label><label>Tecnologias<input value={techText} onChange={e=>setTechText(e.target.value)} placeholder="React, TypeScript, API"/></label></div><label>Descrição<textarea rows={5} value={draft.description} onChange={e=>setDraft(d=>({...d,description:e.target.value}))} placeholder="Qual problema resolve? O que você implementou?"/></label><div className="split-grid"><label>Imagem / screenshot (URL)<input type="url" value={draft.imageUrl??''} onChange={e=>setDraft(d=>({...d,imageUrl:e.target.value}))} placeholder="https://..."/></label><label>GitHub<input type="url" value={draft.githubUrl??''} onChange={e=>setDraft(d=>({...d,githubUrl:e.target.value}))} placeholder="https://github.com/..."/></label><label>Demo<input type="url" value={draft.demoUrl??''} onChange={e=>setDraft(d=>({...d,demoUrl:e.target.value}))} placeholder="https://..."/></label></div><div className="button-row"><button className="primary-button" onClick={save}>Salvar projeto</button><button className="secondary-button" onClick={()=>setEditing(false)}>Cancelar</button></div></section>}
 <div className="portfolio-grid">{data.portfolioProjects.map(project=><article className="glass-panel portfolio-card" key={project.id}>{project.imageUrl&&<img src={project.imageUrl} alt={`Imagem do projeto ${project.name}`} loading="lazy"/>}<div className="portfolio-card-body"><div className="card-top"><span className="pill">Projeto</span><div><button className="icon-button" onClick={()=>edit(project)} aria-label="Editar"><Pencil size={16}/></button><button className="icon-button" onClick={()=>confirm(`Excluir ${project.name}?`)&&deletePortfolioProject(project.id)} aria-label="Excluir"><Trash2 size={16}/></button></div></div><h2>{project.name}</h2><p>{project.description}</p><div className="chip-row">{project.technologies.map(t=><span className="chip static" key={t}>{t}</span>)}</div><div className="button-row">{project.githubUrl&&<a className="secondary-button" href={project.githubUrl} target="_blank" rel="noreferrer"><Github size={16}/> GitHub</a>}{project.demoUrl&&<a className="primary-button" href={project.demoUrl} target="_blank" rel="noreferrer"><ExternalLink size={16}/> Abrir demo</a>}</div></div></article>)}</div>
 <section className="glass-panel content-panel"><h2>O que deixa um projeto mais forte?</h2><ul><li>README curto explicando problema, solução e como rodar.</li><li>Interface responsiva.</li><li>Código organizado em arquivos menores.</li><li>Um link funcionando para testar.</li><li>Você conseguir explicar as decisões que tomou.</li></ul></section></div>
}
