import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Link } from 'react-router-dom'
import { lessons } from '../data/lessons'
import { achievements, dailyMinutes, studyMetrics } from '../lib/metrics'
import { useAppState } from '../hooks/useAppState'

export function ProgressPage(){
  const {data}=useAppState(); const m=studyMetrics(data)
  const chart=(['english','investments','programming'] as const).map(course=>{const all=lessons.filter(l=>l.course===course);const done=all.filter(l=>data.completed[l.id]).length;return {name:course==='english'?'Inglês':course==='investments'?'Investimentos':'Programação',concluídas:done,total:all.length,minutos:m.courseMinutes(course)}})
  const days=dailyMinutes(data,28); const accuracy=m.quizQuestions?Math.round(m.quizCorrect/m.quizQuestions*100):0; const badges=achievements(data); const unlocked=badges.filter(x=>x.unlocked)
  return <div className="page progress-page"><section className="page-header glass-panel"><div className="mega-icon">📊</div><div><span className="eyebrow">Seu ritmo</span><h1>Meu progresso</h1><p>Tempo, aulas, quizzes, revisões, metas e sequência — sem transformar estudo em corrida.</p></div></section>
    <div className="progress-stats-grid"><div className="stat-card glass-panel"><strong>{m.completedCount}</strong><span>aulas concluídas</span></div><div className="stat-card glass-panel"><strong>{data.studyMinutes}</strong><span>minutos totais</span></div><div className="stat-card glass-panel"><strong>{m.streak}</strong><span>dias de sequência</span></div><div className="stat-card glass-panel"><strong>{accuracy}%</strong><span>acerto em quizzes</span></div><div className="stat-card glass-panel"><strong>{m.flashReviews}</strong><span>revisões de cards</span></div><div className="stat-card glass-panel"><strong>{m.xp}</strong><span>XP • nível {m.level}</span></div></div>
    <section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Nível {m.level}</span><h2>{m.xp.toLocaleString('pt-BR')} XP</h2></div><span>{m.nextLevelXp.toLocaleString('pt-BR')} XP de referência para a próxima faixa</span></div><div className="progress-line"><span style={{width:`${Math.min(100,m.xp/m.nextLevelXp*100)}%`}}/></div><small>XP é apenas uma visualização de constância. Nenhuma aula fica bloqueada por nível.</small></section>
    <div className="split-grid"><section className="glass-panel chart-panel"><h2>Aulas concluídas por trilha</h2><ResponsiveContainer width="100%" height={300}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" opacity={0.15}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="concluídas" fill="var(--primary)" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></section><section className="glass-panel chart-panel"><h2>Minutos nos últimos 28 dias</h2><ResponsiveContainer width="100%" height={300}><LineChart data={days}><CartesianGrid strokeDasharray="3 3" opacity={0.15}/><XAxis dataKey="date" interval={4}/><YAxis/><Tooltip/><Line type="monotone" dataKey="minutes" stroke="var(--secondary)" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></section></div>
    <section className="glass-panel content-panel"><h2>Tempo por matéria</h2><div className="course-time-bars">{chart.map(row=><article key={row.name}><div><strong>{row.name}</strong><span>{row.minutos} min • {row.concluídas}/{row.total} aulas</span></div><div className="progress-line"><span style={{width:`${Math.min(100,row.concluídas/row.total*100)}%`}}/></div></article>)}</div></section>
    <div className="split-grid"><section className="glass-panel content-panel"><div className="section-heading"><h2>Metas</h2><Link className="text-link" to="/future">Editar metas →</Link></div>{data.goals.map(g=>{const p=g.target?Math.min(100,Math.round(g.current/g.target*100)):0;return <article className="progress-goal" key={g.id}><div><strong>{g.title}</strong><span>{p}%</span></div><div className="progress-line"><span style={{width:`${p}%`}}/></div></article>})}</section><section className="glass-panel content-panel"><div className="section-heading"><h2>Conquistas</h2><Link className="text-link" to="/profile">Ver perfil →</Link></div><div className="achievement-mini-grid">{badges.map(a=><article key={a.id} className={a.unlocked?'unlocked':''}><span>{a.icon}</span><div><strong>{a.title}</strong><small>{a.unlocked?'Conquistada':a.description}</small></div></article>)}</div><small>{unlocked.length}/{badges.length} desbloqueadas.</small></section></div>
    <section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow">Calendário</span><h2>Hoje {m.todayMinutes} min • semana {m.weeklyMinutes} min • mês {m.monthlyMinutes} min</h2></div><Link className="secondary-button" to="/calendar">Abrir calendário</Link></div></section>
  </div>
}
