import { FormEvent, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Clock3, Search, Trash2 } from 'lucide-react'
import { lessons } from '../data/lessons'
import { countries } from '../data/countries'
import { careers } from '../data/careers'
import { wages } from '../data/wages'
import { occupationWages } from '../data/occupationWages'
import { formatMoney, hourlyEquivalent, monthlyEquivalent } from '../lib/wageMath'
import { occupationHourly, occupationMonthly } from '../lib/occupationWageMath'
import { useAppState } from '../hooks/useAppState'
import type { CourseId } from '../types'

const countryMap=new Map(countries.map(c=>[c.id,c]))
type Category='all'|'lessons'|'countries'|'careers'|'salaries'|'cities'|'notes'
const stopWords=new Set(['qual','quais','como','funciona','funcionar','entre','uma','um','de','do','da','dos','das','e','o','a','por','quanto','ganha','ganham','no','na','nos','nas','para','me','mostra','mostrar','diferença','diferenca'])
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9+#. ]/g,' ').replace(/\s+/g,' ').trim()
const tokens=(query:string)=>normalize(query).split(' ').filter(token=>token.length>1&&!stopWords.has(token))
const scoreText=(query:string,text:string)=>{
  const q=normalize(query), hay=normalize(text); if(!q)return 1
  let score=hay.includes(q)?60:0
  const parts=tokens(query); if(parts.length===0)return score
  for(const token of parts){if(hay.includes(token))score+=12;if(hay.startsWith(token))score+=5}
  if(parts.every(token=>hay.includes(token)))score+=35
  return score
}
const withScore=<T,>(items:T[],query:string,text:(item:T)=>string)=>items.map(item=>({item,score:scoreText(query,text(item))})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).map(x=>x.item)

export function SearchPage(){
  const {data,recordSearch,clearSearchHistory}=useAppState(); const [q,setQ]=useState(''); const [category,setCategory]=useState<Category>('all'); const [course,setCourse]=useState<'all'|CourseId>('all'); const [level,setLevel]=useState('all'); const [duration,setDuration]=useState('all'); const [status,setStatus]=useState<'all'|'done'|'open'>('all'); const query=q.trim()
  const submit=(event?:FormEvent)=>{event?.preventDefault();if(query)recordSearch(query)}
  const lessonResults=useMemo(()=>{if(category!=='all'&&category!=='lessons')return[];let pool=lessons.filter(x=>{if(course!=='all'&&x.course!==course)return false;if(level!=='all'&&x.level!==level)return false;if(duration==='short'&&x.estimatedMinutes>10)return false;if(duration==='medium'&&(x.estimatedMinutes<=10||x.estimatedMinutes>20))return false;if(duration==='long'&&x.estimatedMinutes<=20)return false;if(status==='done'&&!data.completed[x.id])return false;if(status==='open'&&data.completed[x.id])return false;return true});return query?withScore(pool,query,x=>`${x.title} ${x.description} ${x.module} ${x.tags.join(' ')} ${x.content.join(' ')} ${x.examples.join(' ')}`).slice(0,40):[]},[query,category,course,level,duration,status,data.completed])
  const countryResults=useMemo(()=>category!=='all'&&category!=='countries'?[]:query?withScore(countries,query,x=>`${x.name} ${x.capital} ${x.languages.join(' ')} ${x.cities.join(' ')} ${x.region} ${x.bestFor.join(' ')} ${x.pros.join(' ')}`).slice(0,24):[],[query,category])
  const allCities=useMemo(()=>countries.flatMap(c=>c.cities.map(city=>({city,country:c}))),[])
  const cityResults=useMemo(()=>category!=='all'&&category!=='cities'?[]:query?withScore(allCities,query,x=>`${x.city} ${x.country.name} ${x.country.region} ${x.country.languages.join(' ')}`).slice(0,30):[],[query,category,allCities])
  const careerResults=useMemo(()=>category!=='all'&&category!=='careers'?[]:query?withScore(careers,query,x=>`${x.name} ${x.summary} ${x.skills.join(' ')} ${x.roadmap.join(' ')} ${(x.technologies??[]).join(' ')}`).slice(0,20):[],[query,category])
  const wageResults=useMemo(()=>category!=='all'&&category!=='salaries'?[]:query?withScore(wages,query,x=>{const c=countryMap.get(x.countryId);return `${c?.name??''} salario minimo piso ${x.headline} ${x.currency}`}).slice(0,20):[],[query,category])
  const occupationResults=useMemo(()=>category!=='all'&&category!=='salaries'?[]:query?withScore(occupationWages,query,x=>{const c=countryMap.get(x.countryId);return `${c?.name??''} salario profissao carreira ${x.occupation} ${x.currency} ${x.careerIds.join(' ')}`}).slice(0,24):[],[query,category])
  const noteResults=useMemo(()=>{if(category!=='all'&&category!=='notes')return[];const pool=Object.entries(data.notes).filter(([,note])=>note.trim()).map(([id,note])=>({id,note,lesson:lessons.find(l=>l.id===id),tags:data.noteTags[id]??[]}));return query?withScore(pool,query,x=>`${x.note} ${x.lesson?.title??''} ${x.tags.join(' ')}`).slice(0,20):[]},[query,category,data.notes,data.noteTags])
  const levels=[...new Set(lessons.map(l=>l.level))]
  const total=lessonResults.length+countryResults.length+cityResults.length+careerResults.length+wageResults.length+occupationResults.length+noteResults.length
  const suggestions=useMemo(()=>{if(query.length<2)return[];const base=[...countries.map(c=>({label:`${c.flag} ${c.name}`,path:`/countries/${c.id}`,text:`${c.name} ${c.capital} ${c.cities.join(' ')}`})),...lessons.slice(0,160).map(l=>({label:l.title,path:`/lesson/${l.id}`,text:`${l.title} ${l.tags.join(' ')}`})),...careers.map(c=>({label:`${c.icon} ${c.name}`,path:`/careers/${c.id}`,text:`${c.name} ${c.skills.join(' ')}`}))];return withScore(base,query,x=>x.text).slice(0,6)},[query])
  return <div className="page search-page"><section className="page-header glass-panel"><Search className="mega-icon-svg"/><div><span className="eyebrow">Busca universal</span><h1>Pergunte do seu jeito.</h1><p>“Qual diferença entre house e home?”, “salário programador Irlanda”, “como funciona CDI” — a busca separa palavras importantes e ordena por relevância.</p></div></section><section className="search-controls glass-panel"><form className="search-box" onSubmit={submit}><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Ex.: quanto ganha eletricista no Canadá..."/><button type="submit" className="primary-button">Buscar</button></form>{query&&suggestions.length>0&&<div className="search-suggestions">{suggestions.map(item=><Link key={`${item.path}-${item.label}`} to={item.path} onClick={()=>recordSearch(query)}>{item.label}<span>→</span></Link>)}</div>}<div className="search-filter-grid"><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value as Category)}><option value="all">Tudo</option><option value="lessons">Aulas</option><option value="countries">Países</option><option value="cities">Cidades</option><option value="careers">Carreiras</option><option value="salaries">Salários</option><option value="notes">Minhas notas</option></select></label><label>Matéria<select value={course} onChange={e=>setCourse(e.target.value as typeof course)}><option value="all">Todas</option><option value="english">Inglês</option><option value="investments">Investimentos</option><option value="programming">Programação</option></select></label><label>Nível<select value={level} onChange={e=>setLevel(e.target.value)}><option value="all">Todos</option>{levels.map(x=><option key={x}>{x}</option>)}</select></label><label>Duração<select value={duration} onChange={e=>setDuration(e.target.value)}><option value="all">Qualquer</option><option value="short">Até 10 min</option><option value="medium">11–20 min</option><option value="long">Mais de 20 min</option></select></label><label>Progresso<select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">Tudo</option><option value="open">Não concluído</option><option value="done">Concluído</option></select></label></div>{query&&<small>{total} resultado(s) carregados para os filtros atuais.</small>}</section>
    {!query&&data.searchHistory.length>0&&<section className="glass-panel content-panel"><div className="section-heading"><div><span className="eyebrow"><Clock3 size={15}/> Histórico</span><h2>Pesquisas recentes</h2></div><button className="text-button" onClick={clearSearchHistory}><Trash2 size={16}/> Limpar</button></div><div className="chip-row">{data.searchHistory.map(item=><button className="chip" key={item.searchedAt} onClick={()=>setQ(item.query)}>{item.query}</button>)}</div></section>}
    {query&&<div className="search-sections">
      {lessonResults.length>0&&<section><h2>Aulas ({lessonResults.length})</h2><div className="result-list">{lessonResults.map(x=><Link key={x.id} onClick={()=>recordSearch(query)} to={`/lesson/${x.id}`} className="result-item glass-panel"><strong>{x.title}</strong><span>{x.course==='english'?'Inglês':x.course==='investments'?'Investimentos':'Programação'} • {x.level} • {x.estimatedMinutes} min {data.completed[x.id]?'• ✅':''}</span></Link>)}</div></section>}
      {countryResults.length>0&&<section><h2>Países ({countryResults.length})</h2><div className="result-list">{countryResults.map(x=><Link key={x.id} onClick={()=>recordSearch(query)} to={`/countries/${x.id}`} className="result-item glass-panel"><strong>{x.flag} {x.name}</strong><span>{x.capital} • {x.currency} • {x.region}</span></Link>)}</div></section>}
      {cityResults.length>0&&<section><h2>Cidades ({cityResults.length})</h2><div className="result-list">{cityResults.map(x=><Link key={`${x.country.id}-${x.city}`} onClick={()=>recordSearch(query)} to={`/cities/${x.country.id}/${encodeURIComponent(x.city)}`} className="result-item glass-panel"><strong>{x.country.flag} {x.city}</strong><span>{x.country.name} • {x.country.currency}</span></Link>)}</div></section>}
      {careerResults.length>0&&<section><h2>Carreiras ({careerResults.length})</h2><div className="result-list">{careerResults.map(x=><Link key={x.id} onClick={()=>recordSearch(query)} to={`/careers/${x.id}`} className="result-item glass-panel"><strong>{x.icon} {x.name}</strong><span>{x.summary}</span></Link>)}</div></section>}
      {(wageResults.length>0||occupationResults.length>0)&&<section><h2>Salários ({wageResults.length+occupationResults.length})</h2><div className="result-list">{occupationResults.map(x=>{const c=countryMap.get(x.countryId);const hourly=occupationHourly(x);const monthly=occupationMonthly(x);return <Link key={x.id} onClick={()=>recordSearch(query)} to={`/careers/${x.careerIds[0]}`} className="result-item glass-panel"><strong>{c?.flag} {x.occupation}</strong><span>{c?.name} • {formatMoney(hourly,x.currency)}/h • ≈ {formatMoney(monthly,x.currency)}/mês • {x.referencePeriod}</span></Link>})}{wageResults.map(x=>{const c=countryMap.get(x.countryId);return <Link key={`min-${x.countryId}`} onClick={()=>recordSearch(query)} to={`/countries/${x.countryId}`} className="result-item glass-panel"><strong>{c?.flag} Salário mínimo/piso — {c?.name}</strong><span>{formatMoney(hourlyEquivalent(x),x.currency)}/h • ≈ {formatMoney(monthlyEquivalent(x),x.currency)}/mês</span></Link>})}</div></section>}
      {noteResults.length>0&&<section><div className="section-heading"><h2>Minhas notas ({noteResults.length})</h2><Link className="text-link" to="/notes">Central de notas →</Link></div><div className="result-list">{noteResults.map(x=><Link key={x.id} onClick={()=>recordSearch(query)} to={x.lesson?`/lesson/${x.id}`:'/notes'} className="result-item glass-panel"><strong>📝 {x.lesson?.title??x.id}</strong><span>{x.note.slice(0,130)}{x.note.length>130?'…':''}</span></Link>)}</div></section>}
      {total===0&&<div className="empty glass-panel">Nada encontrado. Tente uma palavra menor ou remova algum filtro.</div>}
    </div>}
  </div>
}
