import { useMemo, useState } from 'react'
import { Calculator, Coins, Percent, PiggyBank, WalletCards } from 'lucide-react'

function formatBRL(v:number){return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}

export function ToolsPage(){
 const [principal,setPrincipal]=useState(1000); const [monthly,setMonthly]=useState(200); const [rate,setRate]=useState(0.8); const [months,setMonths]=useState(60)
 const compound=useMemo(()=>{let total=principal; for(let i=0;i<months;i++) total=total*(1+rate/100)+monthly; return total},[principal,monthly,rate,months])
 const invested=principal+monthly*months
 const [inflationValue,setInflationValue]=useState(1000); const [inflation,setInflation]=useState(5); const [years,setYears]=useState(5)
 const purchasing=inflationValue/Math.pow(1+inflation/100,years)
 const futureCost=inflationValue*Math.pow(1+inflation/100,years)
 const [income,setIncome]=useState(3000); const [rent,setRent]=useState(900); const [food,setFood]=useState(600); const [transport,setTransport]=useState(300); const [bills,setBills]=useState(400); const [leisure,setLeisure]=useState(250)
 const expenses=rent+food+transport+bills+leisure
 const [goal,setGoal]=useState(30000); const [saved,setSaved]=useState(5000); const [goalMonthly,setGoalMonthly]=useState(500)
 const goalMonths=goalMonthly>0?Math.max(0,Math.ceil((goal-saved)/goalMonthly)):0
 const [percentBase,setPercentBase]=useState(2500); const [percent,setPercent]=useState(10)
 const [fxValue,setFxValue]=useState(1000); const [fxRate,setFxRate]=useState(6.2)
 const [simplePrincipal,setSimplePrincipal]=useState(1000); const [simpleRate,setSimpleRate]=useState(1); const [simpleMonths,setSimpleMonths]=useState(12)
 const simpleInterest=simplePrincipal*(simpleRate/100)*simpleMonths
 const [nominalReturn,setNominalReturn]=useState(10); const [realInflation,setRealInflation]=useState(5)
 const realReturn=((1+nominalReturn/100)/(1+realInflation/100)-1)*100
 return <div className="page"><section className="page-header glass-panel"><Calculator className="mega-icon-svg"/><div><span className="eyebrow">Ferramentas educativas</span><h1>Calculadoras e simuladores</h1><p>Use para entender conceitos. Resultados não são recomendação financeira nem previsão garantida.</p></div></section><div className="tool-grid">
 <section className="tool-card glass-panel"><h2><Coins/> Juros compostos</h2><div className="form-grid"><label>Valor inicial<input type="number" value={principal} onChange={e=>setPrincipal(Number(e.target.value))}/></label><label>Aporte mensal<input type="number" value={monthly} onChange={e=>setMonthly(Number(e.target.value))}/></label><label>Taxa mensal (%)<input type="number" step="0.1" value={rate} onChange={e=>setRate(Number(e.target.value))}/></label><label>Meses<input type="number" value={months} onChange={e=>setMonths(Number(e.target.value))}/></label></div><div className="calc-result"><span>Valor final estimado</span><strong>{formatBRL(compound)}</strong><small>Você colocou {formatBRL(invested)}; diferença matemática: {formatBRL(compound-invested)}.</small></div></section>
 <section className="tool-card glass-panel"><h2><Percent/> Inflação e poder de compra</h2><div className="form-grid"><label>Valor hoje<input type="number" value={inflationValue} onChange={e=>setInflationValue(Number(e.target.value))}/></label><label>Inflação anual (%)<input type="number" step="0.1" value={inflation} onChange={e=>setInflation(Number(e.target.value))}/></label><label>Anos<input type="number" value={years} onChange={e=>setYears(Number(e.target.value))}/></label></div><div className="calc-result"><span>Preço futuro equivalente</span><strong>{formatBRL(futureCost)}</strong><small>{formatBRL(inflationValue)} no futuro teria poder de compra aproximado de {formatBRL(purchasing)} em valores de hoje.</small></div></section>
 <section className="tool-card glass-panel"><h2><WalletCards/> Dá para viver?</h2><div className="form-grid"><label>Salário líquido<input type="number" value={income} onChange={e=>setIncome(Number(e.target.value))}/></label><label>Aluguel<input type="number" value={rent} onChange={e=>setRent(Number(e.target.value))}/></label><label>Comida<input type="number" value={food} onChange={e=>setFood(Number(e.target.value))}/></label><label>Transporte<input type="number" value={transport} onChange={e=>setTransport(Number(e.target.value))}/></label><label>Contas<input type="number" value={bills} onChange={e=>setBills(Number(e.target.value))}/></label><label>Lazer<input type="number" value={leisure} onChange={e=>setLeisure(Number(e.target.value))}/></label></div><div className="calc-result"><span>Sobra estimada</span><strong>{formatBRL(income-expenses)}</strong><small>Gastos: {income>0?Math.round(expenses/income*100):0}% da renda. É só uma simulação.</small></div></section>
 <section className="tool-card glass-panel"><h2><PiggyBank/> Meta financeira</h2><div className="form-grid"><label>Meta<input type="number" value={goal} onChange={e=>setGoal(Number(e.target.value))}/></label><label>Já guardado<input type="number" value={saved} onChange={e=>setSaved(Number(e.target.value))}/></label><label>Aporte mensal<input type="number" value={goalMonthly} onChange={e=>setGoalMonthly(Number(e.target.value))}/></label></div><div className="calc-result"><span>Tempo sem considerar rendimento</span><strong>{goalMonths} meses</strong><small>Faltam {formatBRL(Math.max(0,goal-saved))}.</small></div></section>
 <section className="tool-card glass-panel"><h2><Percent/> Calculadora de porcentagem</h2><div className="form-grid"><label>Valor<input type="number" value={percentBase} onChange={e=>setPercentBase(Number(e.target.value))}/></label><label>Porcentagem<input type="number" value={percent} onChange={e=>setPercent(Number(e.target.value))}/></label></div><div className="calc-result"><span>{percent}% de {percentBase}</span><strong>{formatBRL(percentBase*percent/100)}</strong></div></section>
 <section className="tool-card glass-panel"><h2>💱 Conversor com taxa manual</h2><p>Para não inventar câmbio atual, você informa a taxa que quer usar.</p><div className="form-grid"><label>Valor<input type="number" value={fxValue} onChange={e=>setFxValue(Number(e.target.value))}/></label><label>Taxa (R$ por unidade)<input type="number" step="0.01" value={fxRate} onChange={e=>setFxRate(Number(e.target.value))}/></label></div><div className="calc-result"><span>Conversão</span><strong>{fxRate>0?(fxValue/fxRate).toFixed(2):'—'} unidades</strong></div></section>
 <section className="tool-card glass-panel"><h2>📏 Juros simples</h2><div className="form-grid"><label>Capital<input type="number" value={simplePrincipal} onChange={e=>setSimplePrincipal(Number(e.target.value))}/></label><label>Taxa mensal (%)<input type="number" step="0.1" value={simpleRate} onChange={e=>setSimpleRate(Number(e.target.value))}/></label><label>Meses<input type="number" value={simpleMonths} onChange={e=>setSimpleMonths(Number(e.target.value))}/></label></div><div className="calc-result"><span>Montante</span><strong>{formatBRL(simplePrincipal+simpleInterest)}</strong><small>Juros: {formatBRL(simpleInterest)}. Aqui os juros não rendem sobre os juros.</small></div></section>
 <section className="tool-card glass-panel"><h2>🎯 Rentabilidade real</h2><div className="form-grid"><label>Rentabilidade nominal anual (%)<input type="number" step="0.1" value={nominalReturn} onChange={e=>setNominalReturn(Number(e.target.value))}/></label><label>Inflação anual (%)<input type="number" step="0.1" value={realInflation} onChange={e=>setRealInflation(Number(e.target.value))}/></label></div><div className="calc-result"><span>Rentabilidade real aproximada</span><strong>{realReturn.toFixed(2)}%</strong><small>Cálculo exato pela relação entre as taxas, não apenas subtração.</small></div></section>
 <section className="tool-card glass-panel"><h2>🧺 Diversificação visual</h2><p>Exemplo educativo de divisão. Ajuste mentalmente conforme aprende; o site não monta carteira recomendada.</p><div className="portfolio-bars"><span style={{width:'50%'}}>Renda fixa 50%</span><span style={{width:'25%'}}>ETFs 25%</span><span style={{width:'15%'}}>Ações 15%</span><span style={{width:'10%'}}>Internacional 10%</span></div></section>
 <section className="tool-card glass-panel"><h2>🧮 Comparador conceitual</h2><p>Compare qualquer investimento sempre por quatro perguntas:</p><ol><li>Qual o risco?</li><li>Quando posso retirar?</li><li>Qual o prazo?</li><li>Quais taxas e impostos?</li></ol></section>
 </div></div>
}
