import { useEffect, useMemo, useState } from 'react'
import { Globe2, Heart, MapPin } from 'lucide-react'
import { Link } from 'react-router-dom'
import { countries } from '../data/countries'
import { countryIso } from '../data/countryIso'
import { useAppState } from '../hooks/useAppState'

interface GeoRow {cca2:string;latlng?:number[]}
const cacheKey='futuro-lab-world-geo-v1'
function project(lat:number,lon:number){return {x:(lon+180)/360*1000,y:(90-lat)/180*500}}

export function WorldMapPage(){
  const {data,toggleFavorite,toggleVisitedCountry,markCountryResearched}=useAppState(); const [geo,setGeo]=useState<Record<string,[number,number]>>(()=>{try{return JSON.parse(localStorage.getItem(cacheKey)??'{}')}catch{return {}}}); const [selected,setSelected]=useState<string|undefined>(); const [loading,setLoading]=useState(Object.keys(geo).length===0)
  useEffect(()=>{if(Object.keys(geo).length)return;fetch('https://restcountries.com/v3.1/all?fields=cca2,latlng').then(r=>r.json()).then((rows:GeoRow[])=>{const next:Record<string,[number,number]>={};for(const row of rows){if(row.cca2&&row.latlng?.length&&row.latlng.length>=2)next[row.cca2]=[row.latlng[0],row.latlng[1]]}setGeo(next);localStorage.setItem(cacheKey,JSON.stringify(next))}).catch(()=>undefined).finally(()=>setLoading(false))},[])
  const points=useMemo(()=>countries.map(c=>{const iso=countryIso[c.id];const pos=geo[iso];return pos?{country:c,...project(pos[0],pos[1])}:null}).filter((x):x is NonNullable<typeof x>=>Boolean(x)),[geo])
  const active=countries.find(c=>c.id===selected)
  const open=(id:string)=>{setSelected(id);markCountryResearched(id)}
  return <div className="page world-map-page"><section className="page-header glass-panel"><Globe2 className="mega-icon-svg"/><div><span className="eyebrow">Mapa interativo</span><h1>Mundo</h1><p>Toque nos pontos para abrir um país, favoritar, comparar mentalmente ou marcar como visitado. As posições vêm de coordenadas públicas e ficam em cache.</p></div></section><section className="world-map-shell glass-panel"><div className="world-map-legend"><span>⭐ favorito</span><span>✓ visitado</span><span>• cadastrado</span></div><svg className="world-map-svg" viewBox="0 0 1000 500" role="img" aria-label="Mapa mundial com países cadastrados"><defs><pattern id="world-grid" width="50" height="50" patternUnits="userSpaceOnUse"><path d="M 50 0 L 0 0 0 50" fill="none" stroke="currentColor" opacity=".08" strokeWidth="1"/></pattern></defs><rect width="1000" height="500" rx="30" fill="url(#world-grid)"/><path className="continent-shape" d="M75 100 Q145 45 265 90 T345 205 Q290 255 225 230 T135 170 Z M420 80 Q520 35 640 80 T815 120 Q900 145 905 230 Q825 250 735 215 T585 205 Q535 285 495 390 Q450 350 460 255 Q400 200 420 80Z M770 325 Q820 300 885 338 T900 410 Q835 455 775 405Z"/>{points.map(({country,x,y})=>{const fav=data.favorites.includes(`country:${country.id}`);const visited=data.visitedCountries.includes(country.id);return <g key={country.id} className={selected===country.id?'map-point active':'map-point'} transform={`translate(${x} ${y})`} onClick={()=>open(country.id)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')open(country.id)}} aria-label={`${country.name}${visited?', visitado':''}${fav?', favorito':''}`}><circle r={selected===country.id?10:7}/>{fav&&<text x="10" y="-7">★</text>}{visited&&<text x="10" y="10">✓</text>}<title>{country.name}</title></g>})}</svg>{loading&&<div className="map-loading">Carregando coordenadas…</div>}<small>Mapa esquemático em projeção equiretangular. Serve para navegação e localização aproximada, não para medir distâncias ou fronteiras.</small></section>{active&&<section className="map-country-card glass-panel"><span className="giant-flag">{active.flag}</span><div><span className="eyebrow">{active.region}</span><h2>{active.name}</h2><p>{active.capital} • {active.currency} • {active.languages.join(', ')}</p><div className="tags">{active.bestFor.slice(0,4).map(x=><span key={x}>{x}</span>)}</div></div><div className="map-card-actions"><button className="icon-button" onClick={()=>toggleFavorite(`country:${active.id}`)} aria-label="Favoritar"><Heart fill={data.favorites.includes(`country:${active.id}`)?'currentColor':'none'}/></button><button className={data.visitedCountries.includes(active.id)?'chip selected':'chip'} onClick={()=>toggleVisitedCountry(active.id)}><MapPin size={14}/>{data.visitedCountries.includes(active.id)?'Visitado':'Marcar visitado'}</button><Link className="primary-button" to={`/countries/${active.id}`}>Abrir país</Link></div></section>}</div>
}
